/*
 * Created on 24 Þub 2016 ( Time 15:56:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.BankTrans;
import org.demo.bean.GlobalTransPoint;
import org.demo.bean.Bank;
import org.demo.bean.BankTransSource;
import org.demo.bean.GlobalPrivateCode;
import org.demo.bean.BankExpense;

//--- Services 
import org.demo.business.service.BankTransService;
import org.demo.business.service.GlobalTransPointService;
import org.demo.business.service.BankService;
import org.demo.business.service.BankTransSourceService;
import org.demo.business.service.GlobalPrivateCodeService;
import org.demo.business.service.BankExpenseService;

//--- List Items 
import org.demo.web.listitem.GlobalTransPointListItem;
import org.demo.web.listitem.BankListItem;
import org.demo.web.listitem.BankTransSourceListItem;
import org.demo.web.listitem.GlobalPrivateCodeListItem;
import org.demo.web.listitem.BankExpenseListItem;

/**
 * Spring MVC controller for 'BankTrans' management.
 */
@Controller
@RequestMapping("/bankTrans")
public class BankTransController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "bankTrans";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "bankTrans/form";
	private static final String JSP_LIST   = "bankTrans/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/bankTrans/create";
	private static final String SAVE_ACTION_UPDATE   = "/bankTrans/update";

	//--- Main entity service
	@Resource
    private BankTransService bankTransService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private GlobalTransPointService globalTransPointService; // Injected by Spring
	@Resource
    private BankService bankService; // Injected by Spring
	@Resource
    private BankTransSourceService bankTransSourceService; // Injected by Spring
	@Resource
    private GlobalPrivateCodeService globalPrivateCodeService; // Injected by Spring
	@Resource
    private BankExpenseService bankExpenseService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BankTransController() {
		super(BankTransController.class, MAIN_ENTITY_NAME );
		log("BankTransController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "GlobalTransPoint"
	 * @param model
	 */
	private void populateListOfGlobalTransPointItems(Model model) {
		List<GlobalTransPoint> list = globalTransPointService.findAll();
		List<GlobalTransPointListItem> items = new LinkedList<GlobalTransPointListItem>();
		for ( GlobalTransPoint globalTransPoint : list ) {
			items.add(new GlobalTransPointListItem( globalTransPoint ) );
		}
		model.addAttribute("listOfGlobalTransPointItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Bank"
	 * @param model
	 */
	private void populateListOfBankItems(Model model) {
		List<Bank> list = bankService.findAll();
		List<BankListItem> items = new LinkedList<BankListItem>();
		for ( Bank bank : list ) {
			items.add(new BankListItem( bank ) );
		}
		model.addAttribute("listOfBankItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "BankTransSource"
	 * @param model
	 */
	private void populateListOfBankTransSourceItems(Model model) {
		List<BankTransSource> list = bankTransSourceService.findAll();
		List<BankTransSourceListItem> items = new LinkedList<BankTransSourceListItem>();
		for ( BankTransSource bankTransSource : list ) {
			items.add(new BankTransSourceListItem( bankTransSource ) );
		}
		model.addAttribute("listOfBankTransSourceItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "GlobalPrivateCode"
	 * @param model
	 */
	private void populateListOfGlobalPrivateCodeItems(Model model) {
		List<GlobalPrivateCode> list = globalPrivateCodeService.findAll();
		List<GlobalPrivateCodeListItem> items = new LinkedList<GlobalPrivateCodeListItem>();
		for ( GlobalPrivateCode globalPrivateCode : list ) {
			items.add(new GlobalPrivateCodeListItem( globalPrivateCode ) );
		}
		model.addAttribute("listOfGlobalPrivateCodeItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "BankExpense"
	 * @param model
	 */
	private void populateListOfBankExpenseItems(Model model) {
		List<BankExpense> list = bankExpenseService.findAll();
		List<BankExpenseListItem> items = new LinkedList<BankExpenseListItem>();
		for ( BankExpense bankExpense : list ) {
			items.add(new BankExpenseListItem( bankExpense ) );
		}
		model.addAttribute("listOfBankExpenseItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param bankTrans
	 */
	private void populateModel(Model model, BankTrans bankTrans, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, bankTrans);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfGlobalTransPointItems(model);
			populateListOfBankItems(model);
			populateListOfBankTransSourceItems(model);
			populateListOfGlobalPrivateCodeItems(model);
			populateListOfBankExpenseItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfBankTransSourceItems(model);
			populateListOfGlobalTransPointItems(model);
			populateListOfGlobalPrivateCodeItems(model);
			populateListOfBankItems(model);
			populateListOfBankExpenseItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of BankTrans found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<BankTrans> list = bankTransService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new BankTrans
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		BankTrans bankTrans = new BankTrans();	
		populateModel( model, bankTrans, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing BankTrans
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		BankTrans bankTrans = bankTransService.findById(id);
		populateModel( model, bankTrans, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bankTrans  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid BankTrans bankTrans, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				BankTrans bankTransCreated = bankTransService.create(bankTrans); 
				model.addAttribute(MAIN_ENTITY_NAME, bankTransCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, bankTrans.getId() );
			} else {
				populateModel( model, bankTrans, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "bankTrans.error.create", e);
			populateModel( model, bankTrans, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bankTrans  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid BankTrans bankTrans, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				BankTrans bankTransSaved = bankTransService.update(bankTrans);
				model.addAttribute(MAIN_ENTITY_NAME, bankTransSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, bankTrans.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, bankTrans, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "bankTrans.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, bankTrans, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			bankTransService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "bankTrans.error.delete", e);
		}
		return redirectToList();
	}

}
