/*
 * Created on 24 Þub 2016 ( Time 15:56:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.ChqbllTransDetail;
import org.demo.bean.ChqbllPayrollDetail;
import org.demo.bean.ChqbllTrans;

//--- Services 
import org.demo.business.service.ChqbllTransDetailService;
import org.demo.business.service.ChqbllPayrollDetailService;
import org.demo.business.service.ChqbllTransService;

//--- List Items 
import org.demo.web.listitem.ChqbllPayrollDetailListItem;
import org.demo.web.listitem.ChqbllTransListItem;

/**
 * Spring MVC controller for 'ChqbllTransDetail' management.
 */
@Controller
@RequestMapping("/chqbllTransDetail")
public class ChqbllTransDetailController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "chqbllTransDetail";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "chqbllTransDetail/form";
	private static final String JSP_LIST   = "chqbllTransDetail/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/chqbllTransDetail/create";
	private static final String SAVE_ACTION_UPDATE   = "/chqbllTransDetail/update";

	//--- Main entity service
	@Resource
    private ChqbllTransDetailService chqbllTransDetailService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ChqbllPayrollDetailService chqbllPayrollDetailService; // Injected by Spring
	@Resource
    private ChqbllTransService chqbllTransService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ChqbllTransDetailController() {
		super(ChqbllTransDetailController.class, MAIN_ENTITY_NAME );
		log("ChqbllTransDetailController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "ChqbllPayrollDetail"
	 * @param model
	 */
	private void populateListOfChqbllPayrollDetailItems(Model model) {
		List<ChqbllPayrollDetail> list = chqbllPayrollDetailService.findAll();
		List<ChqbllPayrollDetailListItem> items = new LinkedList<ChqbllPayrollDetailListItem>();
		for ( ChqbllPayrollDetail chqbllPayrollDetail : list ) {
			items.add(new ChqbllPayrollDetailListItem( chqbllPayrollDetail ) );
		}
		model.addAttribute("listOfChqbllPayrollDetailItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "ChqbllTrans"
	 * @param model
	 */
	private void populateListOfChqbllTransItems(Model model) {
		List<ChqbllTrans> list = chqbllTransService.findAll();
		List<ChqbllTransListItem> items = new LinkedList<ChqbllTransListItem>();
		for ( ChqbllTrans chqbllTrans : list ) {
			items.add(new ChqbllTransListItem( chqbllTrans ) );
		}
		model.addAttribute("listOfChqbllTransItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param chqbllTransDetail
	 */
	private void populateModel(Model model, ChqbllTransDetail chqbllTransDetail, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, chqbllTransDetail);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfChqbllPayrollDetailItems(model);
			populateListOfChqbllTransItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfChqbllTransItems(model);
			populateListOfChqbllPayrollDetailItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of ChqbllTransDetail found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<ChqbllTransDetail> list = chqbllTransDetailService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new ChqbllTransDetail
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		ChqbllTransDetail chqbllTransDetail = new ChqbllTransDetail();	
		populateModel( model, chqbllTransDetail, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing ChqbllTransDetail
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		ChqbllTransDetail chqbllTransDetail = chqbllTransDetailService.findById(id);
		populateModel( model, chqbllTransDetail, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param chqbllTransDetail  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid ChqbllTransDetail chqbllTransDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				ChqbllTransDetail chqbllTransDetailCreated = chqbllTransDetailService.create(chqbllTransDetail); 
				model.addAttribute(MAIN_ENTITY_NAME, chqbllTransDetailCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, chqbllTransDetail.getId() );
			} else {
				populateModel( model, chqbllTransDetail, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "chqbllTransDetail.error.create", e);
			populateModel( model, chqbllTransDetail, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param chqbllTransDetail  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid ChqbllTransDetail chqbllTransDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				ChqbllTransDetail chqbllTransDetailSaved = chqbllTransDetailService.update(chqbllTransDetail);
				model.addAttribute(MAIN_ENTITY_NAME, chqbllTransDetailSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, chqbllTransDetail.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, chqbllTransDetail, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "chqbllTransDetail.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, chqbllTransDetail, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			chqbllTransDetailService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "chqbllTransDetail.error.delete", e);
		}
		return redirectToList();
	}

}
