/*
 * Created on 24 Þub 2016 ( Time 15:56:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.InvoiceTrans;
import org.demo.bean.GlobalTransPoint;
import org.demo.bean.SaleSeller;
import org.demo.bean.Contact;
import org.demo.bean.GlobalPrivateCode;
import org.demo.bean.StockDepot;
import org.demo.bean.InvoiceTransStatus;
import org.demo.bean.InvoiceTransSource;

//--- Services 
import org.demo.business.service.InvoiceTransService;
import org.demo.business.service.GlobalTransPointService;
import org.demo.business.service.SaleSellerService;
import org.demo.business.service.ContactService;
import org.demo.business.service.GlobalPrivateCodeService;
import org.demo.business.service.StockDepotService;
import org.demo.business.service.InvoiceTransStatusService;
import org.demo.business.service.InvoiceTransSourceService;

//--- List Items 
import org.demo.web.listitem.GlobalTransPointListItem;
import org.demo.web.listitem.SaleSellerListItem;
import org.demo.web.listitem.ContactListItem;
import org.demo.web.listitem.GlobalPrivateCodeListItem;
import org.demo.web.listitem.StockDepotListItem;
import org.demo.web.listitem.InvoiceTransStatusListItem;
import org.demo.web.listitem.InvoiceTransSourceListItem;

/**
 * Spring MVC controller for 'InvoiceTrans' management.
 */
@Controller
@RequestMapping("/invoiceTrans")
public class InvoiceTransController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "invoiceTrans";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "invoiceTrans/form";
	private static final String JSP_LIST   = "invoiceTrans/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/invoiceTrans/create";
	private static final String SAVE_ACTION_UPDATE   = "/invoiceTrans/update";

	//--- Main entity service
	@Resource
    private InvoiceTransService invoiceTransService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private GlobalTransPointService globalTransPointService; // Injected by Spring
	@Resource
    private SaleSellerService saleSellerService; // Injected by Spring
	@Resource
    private ContactService contactService; // Injected by Spring
	@Resource
    private GlobalPrivateCodeService globalPrivateCodeService; // Injected by Spring
	@Resource
    private StockDepotService stockDepotService; // Injected by Spring
	@Resource
    private InvoiceTransStatusService invoiceTransStatusService; // Injected by Spring
	@Resource
    private InvoiceTransSourceService invoiceTransSourceService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public InvoiceTransController() {
		super(InvoiceTransController.class, MAIN_ENTITY_NAME );
		log("InvoiceTransController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "GlobalTransPoint"
	 * @param model
	 */
	private void populateListOfGlobalTransPointItems(Model model) {
		List<GlobalTransPoint> list = globalTransPointService.findAll();
		List<GlobalTransPointListItem> items = new LinkedList<GlobalTransPointListItem>();
		for ( GlobalTransPoint globalTransPoint : list ) {
			items.add(new GlobalTransPointListItem( globalTransPoint ) );
		}
		model.addAttribute("listOfGlobalTransPointItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "SaleSeller"
	 * @param model
	 */
	private void populateListOfSaleSellerItems(Model model) {
		List<SaleSeller> list = saleSellerService.findAll();
		List<SaleSellerListItem> items = new LinkedList<SaleSellerListItem>();
		for ( SaleSeller saleSeller : list ) {
			items.add(new SaleSellerListItem( saleSeller ) );
		}
		model.addAttribute("listOfSaleSellerItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Contact"
	 * @param model
	 */
	private void populateListOfContactItems(Model model) {
		List<Contact> list = contactService.findAll();
		List<ContactListItem> items = new LinkedList<ContactListItem>();
		for ( Contact contact : list ) {
			items.add(new ContactListItem( contact ) );
		}
		model.addAttribute("listOfContactItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "GlobalPrivateCode"
	 * @param model
	 */
	private void populateListOfGlobalPrivateCodeItems(Model model) {
		List<GlobalPrivateCode> list = globalPrivateCodeService.findAll();
		List<GlobalPrivateCodeListItem> items = new LinkedList<GlobalPrivateCodeListItem>();
		for ( GlobalPrivateCode globalPrivateCode : list ) {
			items.add(new GlobalPrivateCodeListItem( globalPrivateCode ) );
		}
		model.addAttribute("listOfGlobalPrivateCodeItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "StockDepot"
	 * @param model
	 */
	private void populateListOfStockDepotItems(Model model) {
		List<StockDepot> list = stockDepotService.findAll();
		List<StockDepotListItem> items = new LinkedList<StockDepotListItem>();
		for ( StockDepot stockDepot : list ) {
			items.add(new StockDepotListItem( stockDepot ) );
		}
		model.addAttribute("listOfStockDepotItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "InvoiceTransStatus"
	 * @param model
	 */
	private void populateListOfInvoiceTransStatusItems(Model model) {
		List<InvoiceTransStatus> list = invoiceTransStatusService.findAll();
		List<InvoiceTransStatusListItem> items = new LinkedList<InvoiceTransStatusListItem>();
		for ( InvoiceTransStatus invoiceTransStatus : list ) {
			items.add(new InvoiceTransStatusListItem( invoiceTransStatus ) );
		}
		model.addAttribute("listOfInvoiceTransStatusItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "InvoiceTransSource"
	 * @param model
	 */
	private void populateListOfInvoiceTransSourceItems(Model model) {
		List<InvoiceTransSource> list = invoiceTransSourceService.findAll();
		List<InvoiceTransSourceListItem> items = new LinkedList<InvoiceTransSourceListItem>();
		for ( InvoiceTransSource invoiceTransSource : list ) {
			items.add(new InvoiceTransSourceListItem( invoiceTransSource ) );
		}
		model.addAttribute("listOfInvoiceTransSourceItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param invoiceTrans
	 */
	private void populateModel(Model model, InvoiceTrans invoiceTrans, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, invoiceTrans);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfGlobalTransPointItems(model);
			populateListOfSaleSellerItems(model);
			populateListOfContactItems(model);
			populateListOfGlobalPrivateCodeItems(model);
			populateListOfStockDepotItems(model);
			populateListOfInvoiceTransStatusItems(model);
			populateListOfInvoiceTransSourceItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfContactItems(model);
			populateListOfSaleSellerItems(model);
			populateListOfInvoiceTransSourceItems(model);
			populateListOfGlobalTransPointItems(model);
			populateListOfGlobalPrivateCodeItems(model);
			populateListOfStockDepotItems(model);
			populateListOfInvoiceTransStatusItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of InvoiceTrans found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<InvoiceTrans> list = invoiceTransService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new InvoiceTrans
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		InvoiceTrans invoiceTrans = new InvoiceTrans();	
		populateModel( model, invoiceTrans, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing InvoiceTrans
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		InvoiceTrans invoiceTrans = invoiceTransService.findById(id);
		populateModel( model, invoiceTrans, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param invoiceTrans  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid InvoiceTrans invoiceTrans, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				InvoiceTrans invoiceTransCreated = invoiceTransService.create(invoiceTrans); 
				model.addAttribute(MAIN_ENTITY_NAME, invoiceTransCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, invoiceTrans.getId() );
			} else {
				populateModel( model, invoiceTrans, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "invoiceTrans.error.create", e);
			populateModel( model, invoiceTrans, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param invoiceTrans  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid InvoiceTrans invoiceTrans, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				InvoiceTrans invoiceTransSaved = invoiceTransService.update(invoiceTrans);
				model.addAttribute(MAIN_ENTITY_NAME, invoiceTransSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, invoiceTrans.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, invoiceTrans, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "invoiceTrans.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, invoiceTrans, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			invoiceTransService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "invoiceTrans.error.delete", e);
		}
		return redirectToList();
	}

}
