/*
 * Created on 24 Þub 2016 ( Time 15:56:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.InvoiceTransCurrency;
import org.demo.bean.InvoiceTrans;

//--- Services 
import org.demo.business.service.InvoiceTransCurrencyService;
import org.demo.business.service.InvoiceTransService;

//--- List Items 
import org.demo.web.listitem.InvoiceTransListItem;

/**
 * Spring MVC controller for 'InvoiceTransCurrency' management.
 */
@Controller
@RequestMapping("/invoiceTransCurrency")
public class InvoiceTransCurrencyController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "invoiceTransCurrency";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "invoiceTransCurrency/form";
	private static final String JSP_LIST   = "invoiceTransCurrency/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/invoiceTransCurrency/create";
	private static final String SAVE_ACTION_UPDATE   = "/invoiceTransCurrency/update";

	//--- Main entity service
	@Resource
    private InvoiceTransCurrencyService invoiceTransCurrencyService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private InvoiceTransService invoiceTransService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public InvoiceTransCurrencyController() {
		super(InvoiceTransCurrencyController.class, MAIN_ENTITY_NAME );
		log("InvoiceTransCurrencyController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "InvoiceTrans"
	 * @param model
	 */
	private void populateListOfInvoiceTransItems(Model model) {
		List<InvoiceTrans> list = invoiceTransService.findAll();
		List<InvoiceTransListItem> items = new LinkedList<InvoiceTransListItem>();
		for ( InvoiceTrans invoiceTrans : list ) {
			items.add(new InvoiceTransListItem( invoiceTrans ) );
		}
		model.addAttribute("listOfInvoiceTransItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param invoiceTransCurrency
	 */
	private void populateModel(Model model, InvoiceTransCurrency invoiceTransCurrency, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, invoiceTransCurrency);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfInvoiceTransItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfInvoiceTransItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of InvoiceTransCurrency found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<InvoiceTransCurrency> list = invoiceTransCurrencyService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new InvoiceTransCurrency
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		InvoiceTransCurrency invoiceTransCurrency = new InvoiceTransCurrency();	
		populateModel( model, invoiceTransCurrency, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing InvoiceTransCurrency
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		InvoiceTransCurrency invoiceTransCurrency = invoiceTransCurrencyService.findById(id);
		populateModel( model, invoiceTransCurrency, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param invoiceTransCurrency  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid InvoiceTransCurrency invoiceTransCurrency, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				InvoiceTransCurrency invoiceTransCurrencyCreated = invoiceTransCurrencyService.create(invoiceTransCurrency); 
				model.addAttribute(MAIN_ENTITY_NAME, invoiceTransCurrencyCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, invoiceTransCurrency.getId() );
			} else {
				populateModel( model, invoiceTransCurrency, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "invoiceTransCurrency.error.create", e);
			populateModel( model, invoiceTransCurrency, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param invoiceTransCurrency  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid InvoiceTransCurrency invoiceTransCurrency, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				InvoiceTransCurrency invoiceTransCurrencySaved = invoiceTransCurrencyService.update(invoiceTransCurrency);
				model.addAttribute(MAIN_ENTITY_NAME, invoiceTransCurrencySaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, invoiceTransCurrency.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, invoiceTransCurrency, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "invoiceTransCurrency.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, invoiceTransCurrency, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			invoiceTransCurrencyService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "invoiceTransCurrency.error.delete", e);
		}
		return redirectToList();
	}

}
