/*
 * Created on 24 Þub 2016 ( Time 15:56:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.StockCostingDetail;
import org.demo.bean.Stock;
import org.demo.bean.StockCosting;

//--- Services 
import org.demo.business.service.StockCostingDetailService;
import org.demo.business.service.StockService;
import org.demo.business.service.StockCostingService;

//--- List Items 
import org.demo.web.listitem.StockListItem;
import org.demo.web.listitem.StockCostingListItem;

/**
 * Spring MVC controller for 'StockCostingDetail' management.
 */
@Controller
@RequestMapping("/stockCostingDetail")
public class StockCostingDetailController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "stockCostingDetail";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "stockCostingDetail/form";
	private static final String JSP_LIST   = "stockCostingDetail/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/stockCostingDetail/create";
	private static final String SAVE_ACTION_UPDATE   = "/stockCostingDetail/update";

	//--- Main entity service
	@Resource
    private StockCostingDetailService stockCostingDetailService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private StockService stockService; // Injected by Spring
	@Resource
    private StockCostingService stockCostingService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public StockCostingDetailController() {
		super(StockCostingDetailController.class, MAIN_ENTITY_NAME );
		log("StockCostingDetailController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Stock"
	 * @param model
	 */
	private void populateListOfStockItems(Model model) {
		List<Stock> list = stockService.findAll();
		List<StockListItem> items = new LinkedList<StockListItem>();
		for ( Stock stock : list ) {
			items.add(new StockListItem( stock ) );
		}
		model.addAttribute("listOfStockItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "StockCosting"
	 * @param model
	 */
	private void populateListOfStockCostingItems(Model model) {
		List<StockCosting> list = stockCostingService.findAll();
		List<StockCostingListItem> items = new LinkedList<StockCostingListItem>();
		for ( StockCosting stockCosting : list ) {
			items.add(new StockCostingListItem( stockCosting ) );
		}
		model.addAttribute("listOfStockCostingItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param stockCostingDetail
	 */
	private void populateModel(Model model, StockCostingDetail stockCostingDetail, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, stockCostingDetail);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfStockItems(model);
			populateListOfStockCostingItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfStockCostingItems(model);
			populateListOfStockItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of StockCostingDetail found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<StockCostingDetail> list = stockCostingDetailService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new StockCostingDetail
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		StockCostingDetail stockCostingDetail = new StockCostingDetail();	
		populateModel( model, stockCostingDetail, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing StockCostingDetail
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		StockCostingDetail stockCostingDetail = stockCostingDetailService.findById(id);
		populateModel( model, stockCostingDetail, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param stockCostingDetail  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid StockCostingDetail stockCostingDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				StockCostingDetail stockCostingDetailCreated = stockCostingDetailService.create(stockCostingDetail); 
				model.addAttribute(MAIN_ENTITY_NAME, stockCostingDetailCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, stockCostingDetail.getId() );
			} else {
				populateModel( model, stockCostingDetail, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "stockCostingDetail.error.create", e);
			populateModel( model, stockCostingDetail, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param stockCostingDetail  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid StockCostingDetail stockCostingDetail, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				StockCostingDetail stockCostingDetailSaved = stockCostingDetailService.update(stockCostingDetail);
				model.addAttribute(MAIN_ENTITY_NAME, stockCostingDetailSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, stockCostingDetail.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, stockCostingDetail, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "stockCostingDetail.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, stockCostingDetail, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			stockCostingDetailService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "stockCostingDetail.error.delete", e);
		}
		return redirectToList();
	}

}
