/*
 * Created on 24 Þub 2016 ( Time 16:27:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.StockPriceUpdateDetail;
import org.demo.bean.jpa.StockPriceUpdateDetailEntity;
import org.demo.bean.jpa.StockPriceUpdateEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class StockPriceUpdateDetailServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public StockPriceUpdateDetailServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'StockPriceUpdateDetailEntity' to 'StockPriceUpdateDetail'
	 * @param stockPriceUpdateDetailEntity
	 */
	public StockPriceUpdateDetail mapStockPriceUpdateDetailEntityToStockPriceUpdateDetail(StockPriceUpdateDetailEntity stockPriceUpdateDetailEntity) {
		if(stockPriceUpdateDetailEntity == null) {
			return null;
		}

		//--- Generic mapping 
		StockPriceUpdateDetail stockPriceUpdateDetail = map(stockPriceUpdateDetailEntity, StockPriceUpdateDetail.class);

		//--- Link mapping ( link to StockPriceUpdate )
		if(stockPriceUpdateDetailEntity.getStockPriceUpdate() != null) {
			stockPriceUpdateDetail.setPriceUpdateId(stockPriceUpdateDetailEntity.getStockPriceUpdate().getId());
		}
		return stockPriceUpdateDetail;
	}
	
	/**
	 * Mapping from 'StockPriceUpdateDetail' to 'StockPriceUpdateDetailEntity'
	 * @param stockPriceUpdateDetail
	 * @param stockPriceUpdateDetailEntity
	 */
	public void mapStockPriceUpdateDetailToStockPriceUpdateDetailEntity(StockPriceUpdateDetail stockPriceUpdateDetail, StockPriceUpdateDetailEntity stockPriceUpdateDetailEntity) {
		if(stockPriceUpdateDetail == null) {
			return;
		}

		//--- Generic mapping 
		map(stockPriceUpdateDetail, stockPriceUpdateDetailEntity);

		//--- Link mapping ( link : stockPriceUpdateDetail )
		if( hasLinkToStockPriceUpdate(stockPriceUpdateDetail) ) {
			StockPriceUpdateEntity stockPriceUpdate1 = new StockPriceUpdateEntity();
			stockPriceUpdate1.setId( stockPriceUpdateDetail.getPriceUpdateId() );
			stockPriceUpdateDetailEntity.setStockPriceUpdate( stockPriceUpdate1 );
		} else {
			stockPriceUpdateDetailEntity.setStockPriceUpdate( null );
		}

	}
	
	/**
	 * Verify that StockPriceUpdate id is valid.
	 * @param StockPriceUpdate StockPriceUpdate
	 * @return boolean
	 */
	private boolean hasLinkToStockPriceUpdate(StockPriceUpdateDetail stockPriceUpdateDetail) {
		if(stockPriceUpdateDetail.getPriceUpdateId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}