/*
 * Created on 24 Þub 2016 ( Time 16:27:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.WaybillTransStatus;
import org.demo.bean.jpa.WaybillTransStatusEntity;
import org.demo.bean.jpa.WaybillTransStatusEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WaybillTransStatusServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WaybillTransStatusServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WaybillTransStatusEntity' to 'WaybillTransStatus'
	 * @param waybillTransStatusEntity
	 */
	public WaybillTransStatus mapWaybillTransStatusEntityToWaybillTransStatus(WaybillTransStatusEntity waybillTransStatusEntity) {
		if(waybillTransStatusEntity == null) {
			return null;
		}

		//--- Generic mapping 
		WaybillTransStatus waybillTransStatus = map(waybillTransStatusEntity, WaybillTransStatus.class);

		//--- Link mapping ( link to WaybillTransStatus )
		if(waybillTransStatusEntity.getWaybillTransStatus() != null) {
			waybillTransStatus.setParentId(waybillTransStatusEntity.getWaybillTransStatus().getId());
		}
		return waybillTransStatus;
	}
	
	/**
	 * Mapping from 'WaybillTransStatus' to 'WaybillTransStatusEntity'
	 * @param waybillTransStatus
	 * @param waybillTransStatusEntity
	 */
	public void mapWaybillTransStatusToWaybillTransStatusEntity(WaybillTransStatus waybillTransStatus, WaybillTransStatusEntity waybillTransStatusEntity) {
		if(waybillTransStatus == null) {
			return;
		}

		//--- Generic mapping 
		map(waybillTransStatus, waybillTransStatusEntity);

		//--- Link mapping ( link : waybillTransStatus )
		if( hasLinkToWaybillTransStatus(waybillTransStatus) ) {
			WaybillTransStatusEntity waybillTransStatus1 = new WaybillTransStatusEntity();
			waybillTransStatus1.setId( waybillTransStatus.getParentId() );
			waybillTransStatusEntity.setWaybillTransStatus( waybillTransStatus1 );
		} else {
			waybillTransStatusEntity.setWaybillTransStatus( null );
		}

	}
	
	/**
	 * Verify that WaybillTransStatus id is valid.
	 * @param WaybillTransStatus WaybillTransStatus
	 * @return boolean
	 */
	private boolean hasLinkToWaybillTransStatus(WaybillTransStatus waybillTransStatus) {
		if(waybillTransStatus.getParentId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}