/*
 * Created on 24 Þub 2016 ( Time 15:56:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class AdminUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 20 )
    private String username;

    @Size( max = 30 )
    private String title;

    @Size( max = 100 )
    private String email;

    @Size( max = 32 )
    private String authToken;

    @Size( max = 60 )
    private String passwordHash;


    private Boolean isAdmin;


    private Boolean isActive;

    @Size( max = 20 )
    private String profile;


    private Integer workspace;


    private Integer userGroupId;


    private Integer version;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAuthToken( String authToken ) {
        this.authToken = authToken;
    }
    public String getAuthToken() {
        return this.authToken;
    }

    public void setPasswordHash( String passwordHash ) {
        this.passwordHash = passwordHash;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setIsAdmin( Boolean isAdmin ) {
        this.isAdmin = isAdmin;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setProfile( String profile ) {
        this.profile = profile;
    }
    public String getProfile() {
        return this.profile;
    }

    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }

    public void setUserGroupId( Integer userGroupId ) {
        this.userGroupId = userGroupId;
    }
    public Integer getUserGroupId() {
        return this.userGroupId;
    }

    public void setVersion( Integer version ) {
        this.version = version;
    }
    public Integer getVersion() {
        return this.version;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(authToken);
        sb.append("|");
        sb.append(passwordHash);
        sb.append("|");
        sb.append(isAdmin);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(profile);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(userGroupId);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 


}
