/*
 * Created on 24 Þub 2016 ( Time 15:56:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Contact implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 30 )
    private String code;

    @NotNull
    @Size( min = 1, max = 100 )
    private String name;

    @Size( max = 20 )
    private String taxOffice;

    @Size( max = 15 )
    private String taxNumber;

    @Size( max = 11 )
    private String tcKimlik;

    @Size( max = 30 )
    private String relevant;

    @Size( max = 15 )
    private String phone;

    @Size( max = 15 )
    private String fax;

    @Size( max = 15 )
    private String mobilePhone;

    @Size( max = 100 )
    private String address1;

    @Size( max = 100 )
    private String address2;

    @Size( max = 20 )
    private String city;

    @Size( max = 20 )
    private String country;

    @Size( max = 100 )
    private String email;

    @Size( max = 100 )
    private String website;

    @Size( max = 12 )
    private String status;

    @Size( max = 3 )
    private String excCode;

    @Size( max = 65535 )
    private String note;


    private Boolean isActive;

    @Size( max = 20 )
    private String insertBy;


    private Date insertAt;

    @Size( max = 20 )
    private String updateBy;


    private Date updateAt;


    private Integer sellerId;


    private Integer categoryId;


    private Integer priceListId;


    private Integer extraField0Id;


    private Integer extraField1Id;


    private Integer extraField2Id;


    private Integer extraField3Id;


    private Integer extraField4Id;


    private Integer extraField5Id;


    private Integer extraField6Id;


    private Integer extraField7Id;


    private Integer extraField8Id;


    private Integer extraField9Id;

    @NotNull
    private Integer workspace;


    private Integer version;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setTaxOffice( String taxOffice ) {
        this.taxOffice = taxOffice;
    }
    public String getTaxOffice() {
        return this.taxOffice;
    }

    public void setTaxNumber( String taxNumber ) {
        this.taxNumber = taxNumber;
    }
    public String getTaxNumber() {
        return this.taxNumber;
    }

    public void setTcKimlik( String tcKimlik ) {
        this.tcKimlik = tcKimlik;
    }
    public String getTcKimlik() {
        return this.tcKimlik;
    }

    public void setRelevant( String relevant ) {
        this.relevant = relevant;
    }
    public String getRelevant() {
        return this.relevant;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setFax( String fax ) {
        this.fax = fax;
    }
    public String getFax() {
        return this.fax;
    }

    public void setMobilePhone( String mobilePhone ) {
        this.mobilePhone = mobilePhone;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setAddress1( String address1 ) {
        this.address1 = address1;
    }
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress2( String address2 ) {
        this.address2 = address2;
    }
    public String getAddress2() {
        return this.address2;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setCountry( String country ) {
        this.country = country;
    }
    public String getCountry() {
        return this.country;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setWebsite( String website ) {
        this.website = website;
    }
    public String getWebsite() {
        return this.website;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    public void setExcCode( String excCode ) {
        this.excCode = excCode;
    }
    public String getExcCode() {
        return this.excCode;
    }

    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }

    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setInsertBy( String insertBy ) {
        this.insertBy = insertBy;
    }
    public String getInsertBy() {
        return this.insertBy;
    }

    public void setInsertAt( Date insertAt ) {
        this.insertAt = insertAt;
    }
    public Date getInsertAt() {
        return this.insertAt;
    }

    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateAt( Date updateAt ) {
        this.updateAt = updateAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }

    public void setSellerId( Integer sellerId ) {
        this.sellerId = sellerId;
    }
    public Integer getSellerId() {
        return this.sellerId;
    }

    public void setCategoryId( Integer categoryId ) {
        this.categoryId = categoryId;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setPriceListId( Integer priceListId ) {
        this.priceListId = priceListId;
    }
    public Integer getPriceListId() {
        return this.priceListId;
    }

    public void setExtraField0Id( Integer extraField0Id ) {
        this.extraField0Id = extraField0Id;
    }
    public Integer getExtraField0Id() {
        return this.extraField0Id;
    }

    public void setExtraField1Id( Integer extraField1Id ) {
        this.extraField1Id = extraField1Id;
    }
    public Integer getExtraField1Id() {
        return this.extraField1Id;
    }

    public void setExtraField2Id( Integer extraField2Id ) {
        this.extraField2Id = extraField2Id;
    }
    public Integer getExtraField2Id() {
        return this.extraField2Id;
    }

    public void setExtraField3Id( Integer extraField3Id ) {
        this.extraField3Id = extraField3Id;
    }
    public Integer getExtraField3Id() {
        return this.extraField3Id;
    }

    public void setExtraField4Id( Integer extraField4Id ) {
        this.extraField4Id = extraField4Id;
    }
    public Integer getExtraField4Id() {
        return this.extraField4Id;
    }

    public void setExtraField5Id( Integer extraField5Id ) {
        this.extraField5Id = extraField5Id;
    }
    public Integer getExtraField5Id() {
        return this.extraField5Id;
    }

    public void setExtraField6Id( Integer extraField6Id ) {
        this.extraField6Id = extraField6Id;
    }
    public Integer getExtraField6Id() {
        return this.extraField6Id;
    }

    public void setExtraField7Id( Integer extraField7Id ) {
        this.extraField7Id = extraField7Id;
    }
    public Integer getExtraField7Id() {
        return this.extraField7Id;
    }

    public void setExtraField8Id( Integer extraField8Id ) {
        this.extraField8Id = extraField8Id;
    }
    public Integer getExtraField8Id() {
        return this.extraField8Id;
    }

    public void setExtraField9Id( Integer extraField9Id ) {
        this.extraField9Id = extraField9Id;
    }
    public Integer getExtraField9Id() {
        return this.extraField9Id;
    }

    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }

    public void setVersion( Integer version ) {
        this.version = version;
    }
    public Integer getVersion() {
        return this.version;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(taxOffice);
        sb.append("|");
        sb.append(taxNumber);
        sb.append("|");
        sb.append(tcKimlik);
        sb.append("|");
        sb.append(relevant);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(fax);
        sb.append("|");
        sb.append(mobilePhone);
        sb.append("|");
        sb.append(address1);
        sb.append("|");
        sb.append(address2);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(website);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(excCode);
        // attribute 'note' not usable (type = String Long Text)
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(insertBy);
        sb.append("|");
        sb.append(insertAt);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateAt);
        sb.append("|");
        sb.append(sellerId);
        sb.append("|");
        sb.append(categoryId);
        sb.append("|");
        sb.append(priceListId);
        sb.append("|");
        sb.append(extraField0Id);
        sb.append("|");
        sb.append(extraField1Id);
        sb.append("|");
        sb.append(extraField2Id);
        sb.append("|");
        sb.append(extraField3Id);
        sb.append("|");
        sb.append(extraField4Id);
        sb.append("|");
        sb.append(extraField5Id);
        sb.append("|");
        sb.append(extraField6Id);
        sb.append("|");
        sb.append(extraField7Id);
        sb.append("|");
        sb.append(extraField8Id);
        sb.append("|");
        sb.append(extraField9Id);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 


}
