/*
 * Created on 24 Þub 2016 ( Time 15:56:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class GlobalCurrencyRateDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Date date;

    @NotNull
    @Size( min = 1, max = 3 )
    private String code;

    @NotNull
    @Size( min = 1, max = 25 )
    private String name;


    private Double buying;


    private Double selling;


    private Integer currencyRateId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDate( Date date ) {
        this.date = date;
    }
    public Date getDate() {
        return this.date;
    }

    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setBuying( Double buying ) {
        this.buying = buying;
    }
    public Double getBuying() {
        return this.buying;
    }

    public void setSelling( Double selling ) {
        this.selling = selling;
    }
    public Double getSelling() {
        return this.selling;
    }

    public void setCurrencyRateId( Integer currencyRateId ) {
        this.currencyRateId = currencyRateId;
    }
    public Integer getCurrencyRateId() {
        return this.currencyRateId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(buying);
        sb.append("|");
        sb.append(selling);
        sb.append("|");
        sb.append(currencyRateId);
        return sb.toString(); 
    } 


}
