/*
 * JUnit test case for bean GlobalTransPoint
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.GlobalTransPoint ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean GlobalTransPoint
 * 
 * @author Telosys Tools Generator
 *
 */
public class GlobalTransPointTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class GlobalTransPoint getters and setters ..." );
		
		GlobalTransPoint globalTransPoint = new GlobalTransPoint();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		globalTransPoint.setId( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getId() ) ;

		//--- Test setter/getter for field "par1id"  ( type : Integer )
		// System.out.println(" checking field par1id ..." );
		globalTransPoint.setPar1id( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getPar1id() ) ;

		//--- Test setter/getter for field "par2id"  ( type : Integer )
		// System.out.println(" checking field par2id ..." );
		globalTransPoint.setPar2id( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getPar2id() ) ;

		//--- Test setter/getter for field "par3id"  ( type : Integer )
		// System.out.println(" checking field par3id ..." );
		globalTransPoint.setPar3id( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getPar3id() ) ;

		//--- Test setter/getter for field "par4id"  ( type : Integer )
		// System.out.println(" checking field par4id ..." );
		globalTransPoint.setPar4id( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getPar4id() ) ;

		//--- Test setter/getter for field "par5id"  ( type : Integer )
		// System.out.println(" checking field par5id ..." );
		globalTransPoint.setPar5id( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getPar5id() ) ;

		//--- Test setter/getter for field "name"  ( type : String )
		// System.out.println(" checking field name ..." );
		globalTransPoint.setName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalTransPoint.getName() ) ) ;

		//--- Test setter/getter for field "insertBy"  ( type : String )
		// System.out.println(" checking field insertBy ..." );
		globalTransPoint.setInsertBy( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalTransPoint.getInsertBy() ) ) ;

		//--- Test setter/getter for field "insertAt"  ( type : Date )
		// System.out.println(" checking field insertAt ..." );
		globalTransPoint.setInsertAt( dateValue ) ;
		Assert.assertTrue( dateValue.equals( globalTransPoint.getInsertAt() ) );

		//--- Test setter/getter for field "updateBy"  ( type : String )
		// System.out.println(" checking field updateBy ..." );
		globalTransPoint.setUpdateBy( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalTransPoint.getUpdateBy() ) ) ;

		//--- Test setter/getter for field "updateAt"  ( type : Date )
		// System.out.println(" checking field updateAt ..." );
		globalTransPoint.setUpdateAt( dateValue ) ;
		Assert.assertTrue( dateValue.equals( globalTransPoint.getUpdateAt() ) );

		//--- Test setter/getter for field "workspace"  ( type : Integer )
		// System.out.println(" checking field workspace ..." );
		globalTransPoint.setWorkspace( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getWorkspace() ) ;

		//--- Test setter/getter for field "version"  ( type : Integer )
		// System.out.println(" checking field version ..." );
		globalTransPoint.setVersion( integerValue ) ;
		Assert.assertTrue( integerValue == globalTransPoint.getVersion() ) ;

		
	}



}
