/*
 * JUnit test case for bean GlobalProfile
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.GlobalProfile ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean GlobalProfile
 * 
 * @author Telosys Tools Generator
 *
 */
public class GlobalProfileTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class GlobalProfile getters and setters ..." );
		
		GlobalProfile globalProfile = new GlobalProfile();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		globalProfile.setId( integerValue ) ;
		Assert.assertTrue( integerValue == globalProfile.getId() ) ;

		//--- Test setter/getter for field "name"  ( type : String )
		// System.out.println(" checking field name ..." );
		globalProfile.setName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalProfile.getName() ) ) ;

		//--- Test setter/getter for field "description"  ( type : String )
		// System.out.println(" checking field description ..." );
		globalProfile.setDescription( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalProfile.getDescription() ) ) ;

		//--- Test setter/getter for field "isActive"  ( type : Boolean )
		// System.out.println(" checking field isActive ..." );
		globalProfile.setIsActive( true ) ;
		Assert.assertTrue( globalProfile.getIsActive() ) ;
		globalProfile.setIsActive( false ) ;
		Assert.assertFalse( globalProfile.getIsActive() ) ;

		//--- Test setter/getter for field "jsonData"  ( type : String )
		// System.out.println(" checking field jsonData ..." );
		globalProfile.setJsonData( stringValue ) ;
		Assert.assertTrue( stringValue.equals( globalProfile.getJsonData() ) ) ;

		//--- Test setter/getter for field "version"  ( type : Integer )
		// System.out.println(" checking field version ..." );
		globalProfile.setVersion( integerValue ) ;
		Assert.assertTrue( integerValue == globalProfile.getVersion() ) ;

		
	}



}
