/*
 * JUnit test case for bean SafeTransSource
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.SafeTransSource ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean SafeTransSource
 * 
 * @author Telosys Tools Generator
 *
 */
public class SafeTransSourceTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class SafeTransSource getters and setters ..." );
		
		SafeTransSource safeTransSource = new SafeTransSource();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		safeTransSource.setId( integerValue ) ;
		Assert.assertTrue( integerValue == safeTransSource.getId() ) ;

		//--- Test setter/getter for field "name"  ( type : String )
		// System.out.println(" checking field name ..." );
		safeTransSource.setName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( safeTransSource.getName() ) ) ;

		//--- Test setter/getter for field "suitableRight"  ( type : String )
		// System.out.println(" checking field suitableRight ..." );
		safeTransSource.setSuitableRight( stringValue ) ;
		Assert.assertTrue( stringValue.equals( safeTransSource.getSuitableRight() ) ) ;

		//--- Test setter/getter for field "insertBy"  ( type : String )
		// System.out.println(" checking field insertBy ..." );
		safeTransSource.setInsertBy( stringValue ) ;
		Assert.assertTrue( stringValue.equals( safeTransSource.getInsertBy() ) ) ;

		//--- Test setter/getter for field "insertAt"  ( type : Date )
		// System.out.println(" checking field insertAt ..." );
		safeTransSource.setInsertAt( dateValue ) ;
		Assert.assertTrue( dateValue.equals( safeTransSource.getInsertAt() ) );

		//--- Test setter/getter for field "updateBy"  ( type : String )
		// System.out.println(" checking field updateBy ..." );
		safeTransSource.setUpdateBy( stringValue ) ;
		Assert.assertTrue( stringValue.equals( safeTransSource.getUpdateBy() ) ) ;

		//--- Test setter/getter for field "updateAt"  ( type : Date )
		// System.out.println(" checking field updateAt ..." );
		safeTransSource.setUpdateAt( dateValue ) ;
		Assert.assertTrue( dateValue.equals( safeTransSource.getUpdateAt() ) );

		//--- Test setter/getter for field "isActive"  ( type : Boolean )
		// System.out.println(" checking field isActive ..." );
		safeTransSource.setIsActive( true ) ;
		Assert.assertTrue( safeTransSource.getIsActive() ) ;
		safeTransSource.setIsActive( false ) ;
		Assert.assertFalse( safeTransSource.getIsActive() ) ;

		//--- Test setter/getter for field "workspace"  ( type : Integer )
		// System.out.println(" checking field workspace ..." );
		safeTransSource.setWorkspace( integerValue ) ;
		Assert.assertTrue( integerValue == safeTransSource.getWorkspace() ) ;

		//--- Test setter/getter for field "version"  ( type : Integer )
		// System.out.println(" checking field version ..." );
		safeTransSource.setVersion( integerValue ) ;
		Assert.assertTrue( integerValue == safeTransSource.getVersion() ) ;

		
	}



}
