/*
 * JUnit test case for bean StockTransCurrency
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.StockTransCurrency ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean StockTransCurrency
 * 
 * @author Telosys Tools Generator
 *
 */
public class StockTransCurrencyTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class StockTransCurrency getters and setters ..." );
		
		StockTransCurrency stockTransCurrency = new StockTransCurrency();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		stockTransCurrency.setId( integerValue ) ;
		Assert.assertTrue( integerValue == stockTransCurrency.getId() ) ;

		//--- Test setter/getter for field "currency"  ( type : String )
		// System.out.println(" checking field currency ..." );
		stockTransCurrency.setCurrency( stringValue ) ;
		Assert.assertTrue( stringValue.equals( stockTransCurrency.getCurrency() ) ) ;

		//--- Test setter/getter for field "amount"  ( type : Double )
		// System.out.println(" checking field amount ..." );
		stockTransCurrency.setAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == stockTransCurrency.getAmount() ) ;

		//--- Test setter/getter for field "transId"  ( type : Integer )
		// System.out.println(" checking field transId ..." );
		stockTransCurrency.setTransId( integerValue ) ;
		Assert.assertTrue( integerValue == stockTransCurrency.getTransId() ) ;

		
	}



}
