/*
 * JUnit test case for bean WaybillTransDetail
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.WaybillTransDetail ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean WaybillTransDetail
 * 
 * @author Telosys Tools Generator
 *
 */
public class WaybillTransDetailTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class WaybillTransDetail getters and setters ..." );
		
		WaybillTransDetail waybillTransDetail = new WaybillTransDetail();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		waybillTransDetail.setId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getId() ) ;

		//--- Test setter/getter for field "receiptNo"  ( type : Integer )
		// System.out.println(" checking field receiptNo ..." );
		waybillTransDetail.setReceiptNo( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getReceiptNo() ) ;

		//--- Test setter/getter for field "right"  ( type : String )
		// System.out.println(" checking field right ..." );
		waybillTransDetail.setRight( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getRight() ) ) ;

		//--- Test setter/getter for field "transDate"  ( type : Date )
		// System.out.println(" checking field transDate ..." );
		waybillTransDetail.setTransDate( dateValue ) ;
		Assert.assertTrue( dateValue.equals( waybillTransDetail.getTransDate() ) );

		//--- Test setter/getter for field "deliveryDate"  ( type : Date )
		// System.out.println(" checking field deliveryDate ..." );
		waybillTransDetail.setDeliveryDate( dateValue ) ;
		Assert.assertTrue( dateValue.equals( waybillTransDetail.getDeliveryDate() ) );

		//--- Test setter/getter for field "transType"  ( type : String )
		// System.out.println(" checking field transType ..." );
		waybillTransDetail.setTransType( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getTransType() ) ) ;

		//--- Test setter/getter for field "rowNo"  ( type : Integer )
		// System.out.println(" checking field rowNo ..." );
		waybillTransDetail.setRowNo( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getRowNo() ) ;

		//--- Test setter/getter for field "stockId"  ( type : Integer )
		// System.out.println(" checking field stockId ..." );
		waybillTransDetail.setStockId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getStockId() ) ;

		//--- Test setter/getter for field "name"  ( type : String )
		// System.out.println(" checking field name ..." );
		waybillTransDetail.setName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getName() ) ) ;

		//--- Test setter/getter for field "quantity"  ( type : Double )
		// System.out.println(" checking field quantity ..." );
		waybillTransDetail.setQuantity( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getQuantity() ) ;

		//--- Test setter/getter for field "unit"  ( type : String )
		// System.out.println(" checking field unit ..." );
		waybillTransDetail.setUnit( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getUnit() ) ) ;

		//--- Test setter/getter for field "unitRatio"  ( type : Double )
		// System.out.println(" checking field unitRatio ..." );
		waybillTransDetail.setUnitRatio( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getUnitRatio() ) ;

		//--- Test setter/getter for field "basePrice"  ( type : Double )
		// System.out.println(" checking field basePrice ..." );
		waybillTransDetail.setBasePrice( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getBasePrice() ) ;

		//--- Test setter/getter for field "price"  ( type : Double )
		// System.out.println(" checking field price ..." );
		waybillTransDetail.setPrice( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getPrice() ) ;

		//--- Test setter/getter for field "taxRate"  ( type : Double )
		// System.out.println(" checking field taxRate ..." );
		waybillTransDetail.setTaxRate( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getTaxRate() ) ;

		//--- Test setter/getter for field "discountRate1"  ( type : Double )
		// System.out.println(" checking field discountRate1 ..." );
		waybillTransDetail.setDiscountRate1( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getDiscountRate1() ) ;

		//--- Test setter/getter for field "discountRate2"  ( type : Double )
		// System.out.println(" checking field discountRate2 ..." );
		waybillTransDetail.setDiscountRate2( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getDiscountRate2() ) ;

		//--- Test setter/getter for field "discountRate3"  ( type : Double )
		// System.out.println(" checking field discountRate3 ..." );
		waybillTransDetail.setDiscountRate3( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getDiscountRate3() ) ;

		//--- Test setter/getter for field "amount"  ( type : Double )
		// System.out.println(" checking field amount ..." );
		waybillTransDetail.setAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getAmount() ) ;

		//--- Test setter/getter for field "taxAmount"  ( type : Double )
		// System.out.println(" checking field taxAmount ..." );
		waybillTransDetail.setTaxAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getTaxAmount() ) ;

		//--- Test setter/getter for field "discountAmount"  ( type : Double )
		// System.out.println(" checking field discountAmount ..." );
		waybillTransDetail.setDiscountAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getDiscountAmount() ) ;

		//--- Test setter/getter for field "total"  ( type : Double )
		// System.out.println(" checking field total ..." );
		waybillTransDetail.setTotal( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getTotal() ) ;

		//--- Test setter/getter for field "description"  ( type : String )
		// System.out.println(" checking field description ..." );
		waybillTransDetail.setDescription( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getDescription() ) ) ;

		//--- Test setter/getter for field "transYear"  ( type : Integer )
		// System.out.println(" checking field transYear ..." );
		waybillTransDetail.setTransYear( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getTransYear() ) ;

		//--- Test setter/getter for field "transMonth"  ( type : String )
		// System.out.println(" checking field transMonth ..." );
		waybillTransDetail.setTransMonth( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getTransMonth() ) ) ;

		//--- Test setter/getter for field "unit1"  ( type : String )
		// System.out.println(" checking field unit1 ..." );
		waybillTransDetail.setUnit1( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getUnit1() ) ) ;

		//--- Test setter/getter for field "unit2"  ( type : String )
		// System.out.println(" checking field unit2 ..." );
		waybillTransDetail.setUnit2( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getUnit2() ) ) ;

		//--- Test setter/getter for field "unit3"  ( type : String )
		// System.out.println(" checking field unit3 ..." );
		waybillTransDetail.setUnit3( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getUnit3() ) ) ;

		//--- Test setter/getter for field "unit2ratio"  ( type : Double )
		// System.out.println(" checking field unit2ratio ..." );
		waybillTransDetail.setUnit2ratio( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getUnit2ratio() ) ;

		//--- Test setter/getter for field "unit3ratio"  ( type : Double )
		// System.out.println(" checking field unit3ratio ..." );
		waybillTransDetail.setUnit3ratio( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getUnit3ratio() ) ;

		//--- Test setter/getter for field "excCode"  ( type : String )
		// System.out.println(" checking field excCode ..." );
		waybillTransDetail.setExcCode( stringValue ) ;
		Assert.assertTrue( stringValue.equals( waybillTransDetail.getExcCode() ) ) ;

		//--- Test setter/getter for field "excRate"  ( type : Double )
		// System.out.println(" checking field excRate ..." );
		waybillTransDetail.setExcRate( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getExcRate() ) ;

		//--- Test setter/getter for field "excEquivalent"  ( type : Double )
		// System.out.println(" checking field excEquivalent ..." );
		waybillTransDetail.setExcEquivalent( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getExcEquivalent() ) ;

		//--- Test setter/getter for field "plusFactorAmount"  ( type : Double )
		// System.out.println(" checking field plusFactorAmount ..." );
		waybillTransDetail.setPlusFactorAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getPlusFactorAmount() ) ;

		//--- Test setter/getter for field "minusFactorAmount"  ( type : Double )
		// System.out.println(" checking field minusFactorAmount ..." );
		waybillTransDetail.setMinusFactorAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getMinusFactorAmount() ) ;

		//--- Test setter/getter for field "input"  ( type : Double )
		// System.out.println(" checking field input ..." );
		waybillTransDetail.setInput( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getInput() ) ;

		//--- Test setter/getter for field "output"  ( type : Double )
		// System.out.println(" checking field output ..." );
		waybillTransDetail.setOutput( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getOutput() ) ;

		//--- Test setter/getter for field "inTotal"  ( type : Double )
		// System.out.println(" checking field inTotal ..." );
		waybillTransDetail.setInTotal( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getInTotal() ) ;

		//--- Test setter/getter for field "outTotal"  ( type : Double )
		// System.out.println(" checking field outTotal ..." );
		waybillTransDetail.setOutTotal( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getOutTotal() ) ;

		//--- Test setter/getter for field "netInput"  ( type : Double )
		// System.out.println(" checking field netInput ..." );
		waybillTransDetail.setNetInput( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getNetInput() ) ;

		//--- Test setter/getter for field "netOutput"  ( type : Double )
		// System.out.println(" checking field netOutput ..." );
		waybillTransDetail.setNetOutput( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getNetOutput() ) ;

		//--- Test setter/getter for field "netInTotal"  ( type : Double )
		// System.out.println(" checking field netInTotal ..." );
		waybillTransDetail.setNetInTotal( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getNetInTotal() ) ;

		//--- Test setter/getter for field "netOutTotal"  ( type : Double )
		// System.out.println(" checking field netOutTotal ..." );
		waybillTransDetail.setNetOutTotal( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getNetOutTotal() ) ;

		//--- Test setter/getter for field "completed"  ( type : Double )
		// System.out.println(" checking field completed ..." );
		waybillTransDetail.setCompleted( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getCompleted() ) ;

		//--- Test setter/getter for field "cancelled"  ( type : Double )
		// System.out.println(" checking field cancelled ..." );
		waybillTransDetail.setCancelled( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransDetail.getCancelled() ) ;

		//--- Test setter/getter for field "isTransfer"  ( type : Boolean )
		// System.out.println(" checking field isTransfer ..." );
		waybillTransDetail.setIsTransfer( true ) ;
		Assert.assertTrue( waybillTransDetail.getIsTransfer() ) ;
		waybillTransDetail.setIsTransfer( false ) ;
		Assert.assertFalse( waybillTransDetail.getIsTransfer() ) ;

		//--- Test setter/getter for field "transId"  ( type : Integer )
		// System.out.println(" checking field transId ..." );
		waybillTransDetail.setTransId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getTransId() ) ;

		//--- Test setter/getter for field "depotId"  ( type : Integer )
		// System.out.println(" checking field depotId ..." );
		waybillTransDetail.setDepotId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getDepotId() ) ;

		//--- Test setter/getter for field "contactId"  ( type : Integer )
		// System.out.println(" checking field contactId ..." );
		waybillTransDetail.setContactId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getContactId() ) ;

		//--- Test setter/getter for field "sellerId"  ( type : Integer )
		// System.out.println(" checking field sellerId ..." );
		waybillTransDetail.setSellerId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getSellerId() ) ;

		//--- Test setter/getter for field "transSourceId"  ( type : Integer )
		// System.out.println(" checking field transSourceId ..." );
		waybillTransDetail.setTransSourceId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getTransSourceId() ) ;

		//--- Test setter/getter for field "transPointId"  ( type : Integer )
		// System.out.println(" checking field transPointId ..." );
		waybillTransDetail.setTransPointId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getTransPointId() ) ;

		//--- Test setter/getter for field "privateCodeId"  ( type : Integer )
		// System.out.println(" checking field privateCodeId ..." );
		waybillTransDetail.setPrivateCodeId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getPrivateCodeId() ) ;

		//--- Test setter/getter for field "statusId"  ( type : Integer )
		// System.out.println(" checking field statusId ..." );
		waybillTransDetail.setStatusId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getStatusId() ) ;

		//--- Test setter/getter for field "workspace"  ( type : Integer )
		// System.out.println(" checking field workspace ..." );
		waybillTransDetail.setWorkspace( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransDetail.getWorkspace() ) ;

		
	}



}
