/*
 * JUnit test case for bean WaybillTransFactor
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.WaybillTransFactor ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean WaybillTransFactor
 * 
 * @author Telosys Tools Generator
 *
 */
public class WaybillTransFactorTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class WaybillTransFactor getters and setters ..." );
		
		WaybillTransFactor waybillTransFactor = new WaybillTransFactor();
		
		//--- Test setter/getter for field "id"  ( type : Integer )
		// System.out.println(" checking field id ..." );
		waybillTransFactor.setId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransFactor.getId() ) ;

		//--- Test setter/getter for field "effect"  ( type : Double )
		// System.out.println(" checking field effect ..." );
		waybillTransFactor.setEffect( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransFactor.getEffect() ) ;

		//--- Test setter/getter for field "amount"  ( type : Double )
		// System.out.println(" checking field amount ..." );
		waybillTransFactor.setAmount( doubleValue ) ;
		Assert.assertTrue( doubleValue == waybillTransFactor.getAmount() ) ;

		//--- Test setter/getter for field "transId"  ( type : Integer )
		// System.out.println(" checking field transId ..." );
		waybillTransFactor.setTransId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransFactor.getTransId() ) ;

		//--- Test setter/getter for field "factorId"  ( type : Integer )
		// System.out.println(" checking field factorId ..." );
		waybillTransFactor.setFactorId( integerValue ) ;
		Assert.assertTrue( integerValue == waybillTransFactor.getFactorId() ) ;

		
	}



}
