/*
 * Created on 24 Þub 2016 ( Time 16:18:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "global_currency_rate_detail"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="global_currency_rate_detail", catalog="seyhan" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="GlobalCurrencyRateDetailEntity.countAll", query="SELECT COUNT(x) FROM GlobalCurrencyRateDetailEntity x" )
} )
public class GlobalCurrencyRateDetailEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="_date", nullable=false)
    private Date       date         ;

    @Column(name="code", nullable=false, length=3)
    private String     code         ;

    @Column(name="name", nullable=false, length=25)
    private String     name         ;

    @Column(name="buying")
    private Double     buying       ;

    @Column(name="selling")
    private Double     selling      ;

	// "currencyRateId" (column "currency_rate_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="currency_rate_id", referencedColumnName="id")
    private GlobalCurrencyRateEntity globalCurrencyRate;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public GlobalCurrencyRateDetailEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : _date ( DATE ) 
    public void setDate( Date date ) {
        this.date = date;
    }
    public Date getDate() {
        return this.date;
    }

    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : buying ( DOUBLE ) 
    public void setBuying( Double buying ) {
        this.buying = buying;
    }
    public Double getBuying() {
        return this.buying;
    }

    //--- DATABASE MAPPING : selling ( DOUBLE ) 
    public void setSelling( Double selling ) {
        this.selling = selling;
    }
    public Double getSelling() {
        return this.selling;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setGlobalCurrencyRate( GlobalCurrencyRateEntity globalCurrencyRate ) {
        this.globalCurrencyRate = globalCurrencyRate;
    }
    public GlobalCurrencyRateEntity getGlobalCurrencyRate() {
        return this.globalCurrencyRate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(date);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(buying);
        sb.append("|");
        sb.append(selling);
        return sb.toString(); 
    } 

}
