/*
 * Created on 24 Þub 2016 ( Time 16:18:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "invoice_trans_status_history"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="invoice_trans_status_history", catalog="seyhan" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="InvoiceTransStatusHistoryEntity.countAll", query="SELECT COUNT(x) FROM InvoiceTransStatusHistoryEntity x" )
} )
public class InvoiceTransStatusHistoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trans_time")
    private Date       transTime    ;

    @Column(name="trans_id", nullable=false)
    private Integer    transId      ;

    @Column(name="status_id", nullable=false)
    private Integer    statusId     ;

    @Column(name="username", length=20)
    private String     username     ;

    @Column(name="description", length=150)
    private String     description  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public InvoiceTransStatusHistoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : trans_time ( DATETIME ) 
    public void setTransTime( Date transTime ) {
        this.transTime = transTime;
    }
    public Date getTransTime() {
        return this.transTime;
    }

    //--- DATABASE MAPPING : trans_id ( INT ) 
    public void setTransId( Integer transId ) {
        this.transId = transId;
    }
    public Integer getTransId() {
        return this.transId;
    }

    //--- DATABASE MAPPING : status_id ( INT ) 
    public void setStatusId( Integer statusId ) {
        this.statusId = statusId;
    }
    public Integer getStatusId() {
        return this.statusId;
    }

    //--- DATABASE MAPPING : username ( VARCHAR ) 
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(transTime);
        sb.append("|");
        sb.append(transId);
        sb.append("|");
        sb.append(statusId);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
