/*
 * Created on 24 Þub 2016 ( Time 16:18:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "stock_extra_fields"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="stock_extra_fields", catalog="seyhan" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StockExtraFieldsEntity.countAll", query="SELECT COUNT(x) FROM StockExtraFieldsEntity x" )
} )
public class StockExtraFieldsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=30)
    private String     name         ;

    @Column(name="insert_by", length=20)
    private String     insertBy     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insert_at")
    private Date       insertAt     ;

    @Column(name="update_by", length=20)
    private String     updateBy     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_at")
    private Date       updateAt     ;

    @Column(name="is_active")
    private Boolean    isActive     ;

    @Column(name="extra_fields_id")
    private Integer    extraFieldsId ;

    @Column(name="workspace", nullable=false)
    private Integer    workspace    ;

    @Column(name="version")
    private Integer    version      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock ;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting3;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock10;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign9;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList3;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate6;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList2;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting2;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock9;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign8;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate5;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList10;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting10;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock8;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign7;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate4;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList9;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting9;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock7;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign6;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate3;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList8;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting8;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock6;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign5;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList7;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting7;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock5;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign4;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate10;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList6;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate2;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting6;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock4;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign3;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate9;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting5;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList5;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock3;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate8;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock2;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockCostingEntity.class)
    private List<StockCostingEntity> listOfStockCosting4;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockPriceListEntity.class)
    private List<StockPriceListEntity> listOfStockPriceList4;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign10;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=SaleCampaignEntity.class)
    private List<SaleCampaignEntity> listOfSaleCampaign2;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockPriceUpdateEntity.class)
    private List<StockPriceUpdateEntity> listOfStockPriceUpdate7;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StockExtraFieldsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : insert_by ( VARCHAR ) 
    public void setInsertBy( String insertBy ) {
        this.insertBy = insertBy;
    }
    public String getInsertBy() {
        return this.insertBy;
    }

    //--- DATABASE MAPPING : insert_at ( DATETIME ) 
    public void setInsertAt( Date insertAt ) {
        this.insertAt = insertAt;
    }
    public Date getInsertAt() {
        return this.insertAt;
    }

    //--- DATABASE MAPPING : update_by ( VARCHAR ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }

    //--- DATABASE MAPPING : update_at ( DATETIME ) 
    public void setUpdateAt( Date updateAt ) {
        this.updateAt = updateAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }

    //--- DATABASE MAPPING : is_active ( BIT ) 
    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }

    //--- DATABASE MAPPING : extra_fields_id ( INT ) 
    public void setExtraFieldsId( Integer extraFieldsId ) {
        this.extraFieldsId = extraFieldsId;
    }
    public Integer getExtraFieldsId() {
        return this.extraFieldsId;
    }

    //--- DATABASE MAPPING : workspace ( INT ) 
    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }

    //--- DATABASE MAPPING : version ( INT ) 
    public void setVersion( Integer version ) {
        this.version = version;
    }
    public Integer getVersion() {
        return this.version;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfStock( List<StockEntity> listOfStock ) {
        this.listOfStock = listOfStock;
    }
    public List<StockEntity> getListOfStock() {
        return this.listOfStock;
    }

    public void setListOfStockCosting3( List<StockCostingEntity> listOfStockCosting3 ) {
        this.listOfStockCosting3 = listOfStockCosting3;
    }
    public List<StockCostingEntity> getListOfStockCosting3() {
        return this.listOfStockCosting3;
    }

    public void setListOfStock10( List<StockEntity> listOfStock10 ) {
        this.listOfStock10 = listOfStock10;
    }
    public List<StockEntity> getListOfStock10() {
        return this.listOfStock10;
    }

    public void setListOfSaleCampaign9( List<SaleCampaignEntity> listOfSaleCampaign9 ) {
        this.listOfSaleCampaign9 = listOfSaleCampaign9;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign9() {
        return this.listOfSaleCampaign9;
    }

    public void setListOfStockPriceList3( List<StockPriceListEntity> listOfStockPriceList3 ) {
        this.listOfStockPriceList3 = listOfStockPriceList3;
    }
    public List<StockPriceListEntity> getListOfStockPriceList3() {
        return this.listOfStockPriceList3;
    }

    public void setListOfSaleCampaign( List<SaleCampaignEntity> listOfSaleCampaign ) {
        this.listOfSaleCampaign = listOfSaleCampaign;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign() {
        return this.listOfSaleCampaign;
    }

    public void setListOfStockPriceUpdate6( List<StockPriceUpdateEntity> listOfStockPriceUpdate6 ) {
        this.listOfStockPriceUpdate6 = listOfStockPriceUpdate6;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate6() {
        return this.listOfStockPriceUpdate6;
    }

    public void setListOfStockPriceList2( List<StockPriceListEntity> listOfStockPriceList2 ) {
        this.listOfStockPriceList2 = listOfStockPriceList2;
    }
    public List<StockPriceListEntity> getListOfStockPriceList2() {
        return this.listOfStockPriceList2;
    }

    public void setListOfStockCosting2( List<StockCostingEntity> listOfStockCosting2 ) {
        this.listOfStockCosting2 = listOfStockCosting2;
    }
    public List<StockCostingEntity> getListOfStockCosting2() {
        return this.listOfStockCosting2;
    }

    public void setListOfStock9( List<StockEntity> listOfStock9 ) {
        this.listOfStock9 = listOfStock9;
    }
    public List<StockEntity> getListOfStock9() {
        return this.listOfStock9;
    }

    public void setListOfSaleCampaign8( List<SaleCampaignEntity> listOfSaleCampaign8 ) {
        this.listOfSaleCampaign8 = listOfSaleCampaign8;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign8() {
        return this.listOfSaleCampaign8;
    }

    public void setListOfStockPriceUpdate5( List<StockPriceUpdateEntity> listOfStockPriceUpdate5 ) {
        this.listOfStockPriceUpdate5 = listOfStockPriceUpdate5;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate5() {
        return this.listOfStockPriceUpdate5;
    }

    public void setListOfStockPriceList10( List<StockPriceListEntity> listOfStockPriceList10 ) {
        this.listOfStockPriceList10 = listOfStockPriceList10;
    }
    public List<StockPriceListEntity> getListOfStockPriceList10() {
        return this.listOfStockPriceList10;
    }

    public void setListOfStockPriceList( List<StockPriceListEntity> listOfStockPriceList ) {
        this.listOfStockPriceList = listOfStockPriceList;
    }
    public List<StockPriceListEntity> getListOfStockPriceList() {
        return this.listOfStockPriceList;
    }

    public void setListOfStockCosting10( List<StockCostingEntity> listOfStockCosting10 ) {
        this.listOfStockCosting10 = listOfStockCosting10;
    }
    public List<StockCostingEntity> getListOfStockCosting10() {
        return this.listOfStockCosting10;
    }

    public void setListOfStockCosting( List<StockCostingEntity> listOfStockCosting ) {
        this.listOfStockCosting = listOfStockCosting;
    }
    public List<StockCostingEntity> getListOfStockCosting() {
        return this.listOfStockCosting;
    }

    public void setListOfStock8( List<StockEntity> listOfStock8 ) {
        this.listOfStock8 = listOfStock8;
    }
    public List<StockEntity> getListOfStock8() {
        return this.listOfStock8;
    }

    public void setListOfSaleCampaign7( List<SaleCampaignEntity> listOfSaleCampaign7 ) {
        this.listOfSaleCampaign7 = listOfSaleCampaign7;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign7() {
        return this.listOfSaleCampaign7;
    }

    public void setListOfStockPriceUpdate4( List<StockPriceUpdateEntity> listOfStockPriceUpdate4 ) {
        this.listOfStockPriceUpdate4 = listOfStockPriceUpdate4;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate4() {
        return this.listOfStockPriceUpdate4;
    }

    public void setListOfStockPriceList9( List<StockPriceListEntity> listOfStockPriceList9 ) {
        this.listOfStockPriceList9 = listOfStockPriceList9;
    }
    public List<StockPriceListEntity> getListOfStockPriceList9() {
        return this.listOfStockPriceList9;
    }

    public void setListOfStockCosting9( List<StockCostingEntity> listOfStockCosting9 ) {
        this.listOfStockCosting9 = listOfStockCosting9;
    }
    public List<StockCostingEntity> getListOfStockCosting9() {
        return this.listOfStockCosting9;
    }

    public void setListOfStock7( List<StockEntity> listOfStock7 ) {
        this.listOfStock7 = listOfStock7;
    }
    public List<StockEntity> getListOfStock7() {
        return this.listOfStock7;
    }

    public void setListOfSaleCampaign6( List<SaleCampaignEntity> listOfSaleCampaign6 ) {
        this.listOfSaleCampaign6 = listOfSaleCampaign6;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign6() {
        return this.listOfSaleCampaign6;
    }

    public void setListOfStockPriceUpdate3( List<StockPriceUpdateEntity> listOfStockPriceUpdate3 ) {
        this.listOfStockPriceUpdate3 = listOfStockPriceUpdate3;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate3() {
        return this.listOfStockPriceUpdate3;
    }

    public void setListOfStockPriceList8( List<StockPriceListEntity> listOfStockPriceList8 ) {
        this.listOfStockPriceList8 = listOfStockPriceList8;
    }
    public List<StockPriceListEntity> getListOfStockPriceList8() {
        return this.listOfStockPriceList8;
    }

    public void setListOfStockCosting8( List<StockCostingEntity> listOfStockCosting8 ) {
        this.listOfStockCosting8 = listOfStockCosting8;
    }
    public List<StockCostingEntity> getListOfStockCosting8() {
        return this.listOfStockCosting8;
    }

    public void setListOfStock6( List<StockEntity> listOfStock6 ) {
        this.listOfStock6 = listOfStock6;
    }
    public List<StockEntity> getListOfStock6() {
        return this.listOfStock6;
    }

    public void setListOfSaleCampaign5( List<SaleCampaignEntity> listOfSaleCampaign5 ) {
        this.listOfSaleCampaign5 = listOfSaleCampaign5;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign5() {
        return this.listOfSaleCampaign5;
    }

    public void setListOfStockPriceList7( List<StockPriceListEntity> listOfStockPriceList7 ) {
        this.listOfStockPriceList7 = listOfStockPriceList7;
    }
    public List<StockPriceListEntity> getListOfStockPriceList7() {
        return this.listOfStockPriceList7;
    }

    public void setListOfStockCosting7( List<StockCostingEntity> listOfStockCosting7 ) {
        this.listOfStockCosting7 = listOfStockCosting7;
    }
    public List<StockCostingEntity> getListOfStockCosting7() {
        return this.listOfStockCosting7;
    }

    public void setListOfStock5( List<StockEntity> listOfStock5 ) {
        this.listOfStock5 = listOfStock5;
    }
    public List<StockEntity> getListOfStock5() {
        return this.listOfStock5;
    }

    public void setListOfSaleCampaign4( List<SaleCampaignEntity> listOfSaleCampaign4 ) {
        this.listOfSaleCampaign4 = listOfSaleCampaign4;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign4() {
        return this.listOfSaleCampaign4;
    }

    public void setListOfStockPriceUpdate10( List<StockPriceUpdateEntity> listOfStockPriceUpdate10 ) {
        this.listOfStockPriceUpdate10 = listOfStockPriceUpdate10;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate10() {
        return this.listOfStockPriceUpdate10;
    }

    public void setListOfStockPriceList6( List<StockPriceListEntity> listOfStockPriceList6 ) {
        this.listOfStockPriceList6 = listOfStockPriceList6;
    }
    public List<StockPriceListEntity> getListOfStockPriceList6() {
        return this.listOfStockPriceList6;
    }

    public void setListOfStockPriceUpdate2( List<StockPriceUpdateEntity> listOfStockPriceUpdate2 ) {
        this.listOfStockPriceUpdate2 = listOfStockPriceUpdate2;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate2() {
        return this.listOfStockPriceUpdate2;
    }

    public void setListOfStockCosting6( List<StockCostingEntity> listOfStockCosting6 ) {
        this.listOfStockCosting6 = listOfStockCosting6;
    }
    public List<StockCostingEntity> getListOfStockCosting6() {
        return this.listOfStockCosting6;
    }

    public void setListOfStock4( List<StockEntity> listOfStock4 ) {
        this.listOfStock4 = listOfStock4;
    }
    public List<StockEntity> getListOfStock4() {
        return this.listOfStock4;
    }

    public void setListOfSaleCampaign3( List<SaleCampaignEntity> listOfSaleCampaign3 ) {
        this.listOfSaleCampaign3 = listOfSaleCampaign3;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign3() {
        return this.listOfSaleCampaign3;
    }

    public void setListOfStockPriceUpdate9( List<StockPriceUpdateEntity> listOfStockPriceUpdate9 ) {
        this.listOfStockPriceUpdate9 = listOfStockPriceUpdate9;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate9() {
        return this.listOfStockPriceUpdate9;
    }

    public void setListOfStockCosting5( List<StockCostingEntity> listOfStockCosting5 ) {
        this.listOfStockCosting5 = listOfStockCosting5;
    }
    public List<StockCostingEntity> getListOfStockCosting5() {
        return this.listOfStockCosting5;
    }

    public void setListOfStockPriceUpdate( List<StockPriceUpdateEntity> listOfStockPriceUpdate ) {
        this.listOfStockPriceUpdate = listOfStockPriceUpdate;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate() {
        return this.listOfStockPriceUpdate;
    }

    public void setListOfStockPriceList5( List<StockPriceListEntity> listOfStockPriceList5 ) {
        this.listOfStockPriceList5 = listOfStockPriceList5;
    }
    public List<StockPriceListEntity> getListOfStockPriceList5() {
        return this.listOfStockPriceList5;
    }

    public void setListOfStock3( List<StockEntity> listOfStock3 ) {
        this.listOfStock3 = listOfStock3;
    }
    public List<StockEntity> getListOfStock3() {
        return this.listOfStock3;
    }

    public void setListOfStockPriceUpdate8( List<StockPriceUpdateEntity> listOfStockPriceUpdate8 ) {
        this.listOfStockPriceUpdate8 = listOfStockPriceUpdate8;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate8() {
        return this.listOfStockPriceUpdate8;
    }

    public void setListOfStock2( List<StockEntity> listOfStock2 ) {
        this.listOfStock2 = listOfStock2;
    }
    public List<StockEntity> getListOfStock2() {
        return this.listOfStock2;
    }

    public void setListOfStockCosting4( List<StockCostingEntity> listOfStockCosting4 ) {
        this.listOfStockCosting4 = listOfStockCosting4;
    }
    public List<StockCostingEntity> getListOfStockCosting4() {
        return this.listOfStockCosting4;
    }

    public void setListOfStockPriceList4( List<StockPriceListEntity> listOfStockPriceList4 ) {
        this.listOfStockPriceList4 = listOfStockPriceList4;
    }
    public List<StockPriceListEntity> getListOfStockPriceList4() {
        return this.listOfStockPriceList4;
    }

    public void setListOfSaleCampaign10( List<SaleCampaignEntity> listOfSaleCampaign10 ) {
        this.listOfSaleCampaign10 = listOfSaleCampaign10;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign10() {
        return this.listOfSaleCampaign10;
    }

    public void setListOfSaleCampaign2( List<SaleCampaignEntity> listOfSaleCampaign2 ) {
        this.listOfSaleCampaign2 = listOfSaleCampaign2;
    }
    public List<SaleCampaignEntity> getListOfSaleCampaign2() {
        return this.listOfSaleCampaign2;
    }

    public void setListOfStockPriceUpdate7( List<StockPriceUpdateEntity> listOfStockPriceUpdate7 ) {
        this.listOfStockPriceUpdate7 = listOfStockPriceUpdate7;
    }
    public List<StockPriceUpdateEntity> getListOfStockPriceUpdate7() {
        return this.listOfStockPriceUpdate7;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(insertBy);
        sb.append("|");
        sb.append(insertAt);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateAt);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(extraFieldsId);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
