/*
 * Created on 24 Þub 2016 ( Time 16:27:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.AdminUserRight;

/**
 * Business Service Interface for entity AdminUserRight.
 */
public interface AdminUserRightService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	AdminUserRight findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AdminUserRight> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AdminUserRight save(AdminUserRight entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AdminUserRight update(AdminUserRight entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AdminUserRight create(AdminUserRight entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
