/*
 * Created on 24 Þub 2016 ( Time 16:27:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.StockTransSource;

/**
 * Business Service Interface for entity StockTransSource.
 */
public interface StockTransSourceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	StockTransSource findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<StockTransSource> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	StockTransSource save(StockTransSource entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	StockTransSource update(StockTransSource entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	StockTransSource create(StockTransSource entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
