/*
 * Created on 24 Þub 2016 ( Time 16:27:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.StockTransFactor;

/**
 * Business Service Interface for entity StockTransFactor.
 */
public interface StockTransFactorService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	StockTransFactor findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<StockTransFactor> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	StockTransFactor save(StockTransFactor entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	StockTransFactor update(StockTransFactor entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	StockTransFactor create(StockTransFactor entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
