/*
 * Created on 24 Þub 2016 ( Time 16:36:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.demo.bean.ChqbllType;
import org.demo.bean.jpa.ChqbllTypeEntity;
import java.util.Date;
import java.util.List;
import org.demo.business.service.ChqbllTypeService;
import org.demo.business.service.mapping.ChqbllTypeServiceMapper;
import org.demo.data.repository.jpa.ChqbllTypeJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of ChqbllTypeService
 */
@Component
@Transactional
public class ChqbllTypeServiceImpl implements ChqbllTypeService {

	@Resource
	private ChqbllTypeJpaRepository chqbllTypeJpaRepository;

	@Resource
	private ChqbllTypeServiceMapper chqbllTypeServiceMapper;
	
	public ChqbllType findById(Integer id) {
		ChqbllTypeEntity chqbllTypeEntity = chqbllTypeJpaRepository.findOne(id);
		return chqbllTypeServiceMapper.mapChqbllTypeEntityToChqbllType(chqbllTypeEntity);
	}

	public List<ChqbllType> findAll() {
		Iterable<ChqbllTypeEntity> entities = chqbllTypeJpaRepository.findAll();
		List<ChqbllType> beans = new ArrayList<ChqbllType>();
		for(ChqbllTypeEntity chqbllTypeEntity : entities) {
			beans.add(chqbllTypeServiceMapper.mapChqbllTypeEntityToChqbllType(chqbllTypeEntity));
		}
		return beans;
	}

	public ChqbllType save(ChqbllType chqbllType) {
		return update(chqbllType) ;
	}

	public ChqbllType create(ChqbllType chqbllType) {
		ChqbllTypeEntity chqbllTypeEntity = chqbllTypeJpaRepository.findOne(chqbllType.getId());
		if( chqbllTypeEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		chqbllTypeEntity = new ChqbllTypeEntity();
		chqbllTypeServiceMapper.mapChqbllTypeToChqbllTypeEntity(chqbllType, chqbllTypeEntity);
		ChqbllTypeEntity chqbllTypeEntitySaved = chqbllTypeJpaRepository.save(chqbllTypeEntity);
		return chqbllTypeServiceMapper.mapChqbllTypeEntityToChqbllType(chqbllTypeEntitySaved);
	}

	public ChqbllType update(ChqbllType chqbllType) {
		ChqbllTypeEntity chqbllTypeEntity = chqbllTypeJpaRepository.findOne(chqbllType.getId());
		chqbllTypeServiceMapper.mapChqbllTypeToChqbllTypeEntity(chqbllType, chqbllTypeEntity);
		ChqbllTypeEntity chqbllTypeEntitySaved = chqbllTypeJpaRepository.save(chqbllTypeEntity);
		return chqbllTypeServiceMapper.mapChqbllTypeEntityToChqbllType(chqbllTypeEntitySaved);
	}

	public void delete(Integer id) {
		chqbllTypeJpaRepository.delete(id);
	}

	public ChqbllTypeJpaRepository getChqbllTypeJpaRepository() {
		return chqbllTypeJpaRepository;
	}

	public void setChqbllTypeJpaRepository(ChqbllTypeJpaRepository chqbllTypeJpaRepository) {
		this.chqbllTypeJpaRepository = chqbllTypeJpaRepository;
	}

	public ChqbllTypeServiceMapper getChqbllTypeServiceMapper() {
		return chqbllTypeServiceMapper;
	}

	public void setChqbllTypeServiceMapper(ChqbllTypeServiceMapper chqbllTypeServiceMapper) {
		this.chqbllTypeServiceMapper = chqbllTypeServiceMapper;
	}

}
