/*
 * Created on 24 Þub 2016 ( Time 16:36:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.demo.bean.ChqbllDetailHistory;
import org.demo.bean.jpa.ChqbllDetailHistoryEntity;
import java.util.Date;
import org.demo.business.service.ChqbllDetailHistoryService;
import org.demo.business.service.mapping.ChqbllDetailHistoryServiceMapper;
import org.demo.data.repository.jpa.ChqbllDetailHistoryJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of ChqbllDetailHistoryService
 */
@Component
@Transactional
public class ChqbllDetailHistoryServiceImpl implements ChqbllDetailHistoryService {

	@Resource
	private ChqbllDetailHistoryJpaRepository chqbllDetailHistoryJpaRepository;

	@Resource
	private ChqbllDetailHistoryServiceMapper chqbllDetailHistoryServiceMapper;
	
	public ChqbllDetailHistory findById(Integer id) {
		ChqbllDetailHistoryEntity chqbllDetailHistoryEntity = chqbllDetailHistoryJpaRepository.findOne(id);
		return chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryEntityToChqbllDetailHistory(chqbllDetailHistoryEntity);
	}

	public List<ChqbllDetailHistory> findAll() {
		Iterable<ChqbllDetailHistoryEntity> entities = chqbllDetailHistoryJpaRepository.findAll();
		List<ChqbllDetailHistory> beans = new ArrayList<ChqbllDetailHistory>();
		for(ChqbllDetailHistoryEntity chqbllDetailHistoryEntity : entities) {
			beans.add(chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryEntityToChqbllDetailHistory(chqbllDetailHistoryEntity));
		}
		return beans;
	}

	public ChqbllDetailHistory save(ChqbllDetailHistory chqbllDetailHistory) {
		return update(chqbllDetailHistory) ;
	}

	public ChqbllDetailHistory create(ChqbllDetailHistory chqbllDetailHistory) {
		ChqbllDetailHistoryEntity chqbllDetailHistoryEntity = chqbllDetailHistoryJpaRepository.findOne(chqbllDetailHistory.getId());
		if( chqbllDetailHistoryEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		chqbllDetailHistoryEntity = new ChqbllDetailHistoryEntity();
		chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryToChqbllDetailHistoryEntity(chqbllDetailHistory, chqbllDetailHistoryEntity);
		ChqbllDetailHistoryEntity chqbllDetailHistoryEntitySaved = chqbllDetailHistoryJpaRepository.save(chqbllDetailHistoryEntity);
		return chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryEntityToChqbllDetailHistory(chqbllDetailHistoryEntitySaved);
	}

	public ChqbllDetailHistory update(ChqbllDetailHistory chqbllDetailHistory) {
		ChqbllDetailHistoryEntity chqbllDetailHistoryEntity = chqbllDetailHistoryJpaRepository.findOne(chqbllDetailHistory.getId());
		chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryToChqbllDetailHistoryEntity(chqbllDetailHistory, chqbllDetailHistoryEntity);
		ChqbllDetailHistoryEntity chqbllDetailHistoryEntitySaved = chqbllDetailHistoryJpaRepository.save(chqbllDetailHistoryEntity);
		return chqbllDetailHistoryServiceMapper.mapChqbllDetailHistoryEntityToChqbllDetailHistory(chqbllDetailHistoryEntitySaved);
	}

	public void delete(Integer id) {
		chqbllDetailHistoryJpaRepository.delete(id);
	}

	public ChqbllDetailHistoryJpaRepository getChqbllDetailHistoryJpaRepository() {
		return chqbllDetailHistoryJpaRepository;
	}

	public void setChqbllDetailHistoryJpaRepository(ChqbllDetailHistoryJpaRepository chqbllDetailHistoryJpaRepository) {
		this.chqbllDetailHistoryJpaRepository = chqbllDetailHistoryJpaRepository;
	}

	public ChqbllDetailHistoryServiceMapper getChqbllDetailHistoryServiceMapper() {
		return chqbllDetailHistoryServiceMapper;
	}

	public void setChqbllDetailHistoryServiceMapper(ChqbllDetailHistoryServiceMapper chqbllDetailHistoryServiceMapper) {
		this.chqbllDetailHistoryServiceMapper = chqbllDetailHistoryServiceMapper;
	}

}
