/*
 * Created on 24 Þub 2016 ( Time 16:36:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.demo.bean.StockExtraFields;
import org.demo.bean.jpa.StockExtraFieldsEntity;
import java.util.Date;
import java.util.List;
import org.demo.business.service.StockExtraFieldsService;
import org.demo.business.service.mapping.StockExtraFieldsServiceMapper;
import org.demo.data.repository.jpa.StockExtraFieldsJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of StockExtraFieldsService
 */
@Component
@Transactional
public class StockExtraFieldsServiceImpl implements StockExtraFieldsService {

	@Resource
	private StockExtraFieldsJpaRepository stockExtraFieldsJpaRepository;

	@Resource
	private StockExtraFieldsServiceMapper stockExtraFieldsServiceMapper;
	
	public StockExtraFields findById(Integer id) {
		StockExtraFieldsEntity stockExtraFieldsEntity = stockExtraFieldsJpaRepository.findOne(id);
		return stockExtraFieldsServiceMapper.mapStockExtraFieldsEntityToStockExtraFields(stockExtraFieldsEntity);
	}

	public List<StockExtraFields> findAll() {
		Iterable<StockExtraFieldsEntity> entities = stockExtraFieldsJpaRepository.findAll();
		List<StockExtraFields> beans = new ArrayList<StockExtraFields>();
		for(StockExtraFieldsEntity stockExtraFieldsEntity : entities) {
			beans.add(stockExtraFieldsServiceMapper.mapStockExtraFieldsEntityToStockExtraFields(stockExtraFieldsEntity));
		}
		return beans;
	}

	public StockExtraFields save(StockExtraFields stockExtraFields) {
		return update(stockExtraFields) ;
	}

	public StockExtraFields create(StockExtraFields stockExtraFields) {
		StockExtraFieldsEntity stockExtraFieldsEntity = stockExtraFieldsJpaRepository.findOne(stockExtraFields.getId());
		if( stockExtraFieldsEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		stockExtraFieldsEntity = new StockExtraFieldsEntity();
		stockExtraFieldsServiceMapper.mapStockExtraFieldsToStockExtraFieldsEntity(stockExtraFields, stockExtraFieldsEntity);
		StockExtraFieldsEntity stockExtraFieldsEntitySaved = stockExtraFieldsJpaRepository.save(stockExtraFieldsEntity);
		return stockExtraFieldsServiceMapper.mapStockExtraFieldsEntityToStockExtraFields(stockExtraFieldsEntitySaved);
	}

	public StockExtraFields update(StockExtraFields stockExtraFields) {
		StockExtraFieldsEntity stockExtraFieldsEntity = stockExtraFieldsJpaRepository.findOne(stockExtraFields.getId());
		stockExtraFieldsServiceMapper.mapStockExtraFieldsToStockExtraFieldsEntity(stockExtraFields, stockExtraFieldsEntity);
		StockExtraFieldsEntity stockExtraFieldsEntitySaved = stockExtraFieldsJpaRepository.save(stockExtraFieldsEntity);
		return stockExtraFieldsServiceMapper.mapStockExtraFieldsEntityToStockExtraFields(stockExtraFieldsEntitySaved);
	}

	public void delete(Integer id) {
		stockExtraFieldsJpaRepository.delete(id);
	}

	public StockExtraFieldsJpaRepository getStockExtraFieldsJpaRepository() {
		return stockExtraFieldsJpaRepository;
	}

	public void setStockExtraFieldsJpaRepository(StockExtraFieldsJpaRepository stockExtraFieldsJpaRepository) {
		this.stockExtraFieldsJpaRepository = stockExtraFieldsJpaRepository;
	}

	public StockExtraFieldsServiceMapper getStockExtraFieldsServiceMapper() {
		return stockExtraFieldsServiceMapper;
	}

	public void setStockExtraFieldsServiceMapper(StockExtraFieldsServiceMapper stockExtraFieldsServiceMapper) {
		this.stockExtraFieldsServiceMapper = stockExtraFieldsServiceMapper;
	}

}
