/*
 * Created on 24 Þub 2016 ( Time 16:36:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.demo.bean.StockCostingInventory;
import org.demo.bean.jpa.StockCostingInventoryEntity;
import java.util.Date;
import org.demo.business.service.StockCostingInventoryService;
import org.demo.business.service.mapping.StockCostingInventoryServiceMapper;
import org.demo.data.repository.jpa.StockCostingInventoryJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of StockCostingInventoryService
 */
@Component
@Transactional
public class StockCostingInventoryServiceImpl implements StockCostingInventoryService {

	@Resource
	private StockCostingInventoryJpaRepository stockCostingInventoryJpaRepository;

	@Resource
	private StockCostingInventoryServiceMapper stockCostingInventoryServiceMapper;
	
	public StockCostingInventory findById(Integer id) {
		StockCostingInventoryEntity stockCostingInventoryEntity = stockCostingInventoryJpaRepository.findOne(id);
		return stockCostingInventoryServiceMapper.mapStockCostingInventoryEntityToStockCostingInventory(stockCostingInventoryEntity);
	}

	public List<StockCostingInventory> findAll() {
		Iterable<StockCostingInventoryEntity> entities = stockCostingInventoryJpaRepository.findAll();
		List<StockCostingInventory> beans = new ArrayList<StockCostingInventory>();
		for(StockCostingInventoryEntity stockCostingInventoryEntity : entities) {
			beans.add(stockCostingInventoryServiceMapper.mapStockCostingInventoryEntityToStockCostingInventory(stockCostingInventoryEntity));
		}
		return beans;
	}

	public StockCostingInventory save(StockCostingInventory stockCostingInventory) {
		return update(stockCostingInventory) ;
	}

	public StockCostingInventory create(StockCostingInventory stockCostingInventory) {
		StockCostingInventoryEntity stockCostingInventoryEntity = stockCostingInventoryJpaRepository.findOne(stockCostingInventory.getId());
		if( stockCostingInventoryEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		stockCostingInventoryEntity = new StockCostingInventoryEntity();
		stockCostingInventoryServiceMapper.mapStockCostingInventoryToStockCostingInventoryEntity(stockCostingInventory, stockCostingInventoryEntity);
		StockCostingInventoryEntity stockCostingInventoryEntitySaved = stockCostingInventoryJpaRepository.save(stockCostingInventoryEntity);
		return stockCostingInventoryServiceMapper.mapStockCostingInventoryEntityToStockCostingInventory(stockCostingInventoryEntitySaved);
	}

	public StockCostingInventory update(StockCostingInventory stockCostingInventory) {
		StockCostingInventoryEntity stockCostingInventoryEntity = stockCostingInventoryJpaRepository.findOne(stockCostingInventory.getId());
		stockCostingInventoryServiceMapper.mapStockCostingInventoryToStockCostingInventoryEntity(stockCostingInventory, stockCostingInventoryEntity);
		StockCostingInventoryEntity stockCostingInventoryEntitySaved = stockCostingInventoryJpaRepository.save(stockCostingInventoryEntity);
		return stockCostingInventoryServiceMapper.mapStockCostingInventoryEntityToStockCostingInventory(stockCostingInventoryEntitySaved);
	}

	public void delete(Integer id) {
		stockCostingInventoryJpaRepository.delete(id);
	}

	public StockCostingInventoryJpaRepository getStockCostingInventoryJpaRepository() {
		return stockCostingInventoryJpaRepository;
	}

	public void setStockCostingInventoryJpaRepository(StockCostingInventoryJpaRepository stockCostingInventoryJpaRepository) {
		this.stockCostingInventoryJpaRepository = stockCostingInventoryJpaRepository;
	}

	public StockCostingInventoryServiceMapper getStockCostingInventoryServiceMapper() {
		return stockCostingInventoryServiceMapper;
	}

	public void setStockCostingInventoryServiceMapper(StockCostingInventoryServiceMapper stockCostingInventoryServiceMapper) {
		this.stockCostingInventoryServiceMapper = stockCostingInventoryServiceMapper;
	}

}
