/*
 * Created on 24 Þub 2016 ( Time 16:05:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.GlobalCurrency;
import org.demo.web.common.ListItem;

public class GlobalCurrencyListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public GlobalCurrencyListItem(GlobalCurrency globalCurrency) {
		super();

		this.value = ""
			 + globalCurrency.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = globalCurrency.toString();
	}

	public String getValue() {
		return value;
	}

	public String getLabel() {
		return label;
	}

}
