/*
 * Created on 24 Þub 2016 ( Time 16:05:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.WaybillTransSource;
import org.demo.web.common.ListItem;

public class WaybillTransSourceListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public WaybillTransSourceListItem(WaybillTransSource waybillTransSource) {
		super();

		this.value = ""
			 + waybillTransSource.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = waybillTransSource.toString();
	}

	public String getValue() {
		return value;
	}

	public String getLabel() {
		return label;
	}

}
