/*
 * Created on 24 Þub 2016 ( Time 15:56:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.AdminDocument;
import org.demo.business.service.AdminDocumentService;
import org.demo.web.listitem.AdminDocumentListItem;

/**
 * Spring MVC controller for 'AdminDocument' management.
 */
@Controller
public class AdminDocumentRestController {

	@Resource
	private AdminDocumentService adminDocumentService;
	
	@RequestMapping( value="/items/adminDocument",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<AdminDocumentListItem> findAllAsListItems() {
		List<AdminDocument> list = adminDocumentService.findAll();
		List<AdminDocumentListItem> items = new LinkedList<AdminDocumentListItem>();
		for ( AdminDocument adminDocument : list ) {
			items.add(new AdminDocumentListItem( adminDocument ) );
		}
		return items;
	}
	
	@RequestMapping( value="/adminDocument",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<AdminDocument> findAll() {
		return adminDocumentService.findAll();
	}

	@RequestMapping( value="/adminDocument/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminDocument findOne(@PathVariable("id") Integer id) {
		return adminDocumentService.findById(id);
	}
	
	@RequestMapping( value="/adminDocument",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminDocument create(@RequestBody AdminDocument adminDocument) {
		return adminDocumentService.create(adminDocument);
	}

	@RequestMapping( value="/adminDocument/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminDocument update(@PathVariable("id") Integer id, @RequestBody AdminDocument adminDocument) {
		return adminDocumentService.update(adminDocument);
	}

	@RequestMapping( value="/adminDocument/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		adminDocumentService.delete(id);
	}
	
}
