/*
 * Created on 24 Þub 2016 ( Time 15:56:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.AdminExtraFields;
import org.demo.business.service.AdminExtraFieldsService;
import org.demo.web.listitem.AdminExtraFieldsListItem;

/**
 * Spring MVC controller for 'AdminExtraFields' management.
 */
@Controller
public class AdminExtraFieldsRestController {

	@Resource
	private AdminExtraFieldsService adminExtraFieldsService;
	
	@RequestMapping( value="/items/adminExtraFields",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<AdminExtraFieldsListItem> findAllAsListItems() {
		List<AdminExtraFields> list = adminExtraFieldsService.findAll();
		List<AdminExtraFieldsListItem> items = new LinkedList<AdminExtraFieldsListItem>();
		for ( AdminExtraFields adminExtraFields : list ) {
			items.add(new AdminExtraFieldsListItem( adminExtraFields ) );
		}
		return items;
	}
	
	@RequestMapping( value="/adminExtraFields",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<AdminExtraFields> findAll() {
		return adminExtraFieldsService.findAll();
	}

	@RequestMapping( value="/adminExtraFields/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminExtraFields findOne(@PathVariable("id") Integer id) {
		return adminExtraFieldsService.findById(id);
	}
	
	@RequestMapping( value="/adminExtraFields",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminExtraFields create(@RequestBody AdminExtraFields adminExtraFields) {
		return adminExtraFieldsService.create(adminExtraFields);
	}

	@RequestMapping( value="/adminExtraFields/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public AdminExtraFields update(@PathVariable("id") Integer id, @RequestBody AdminExtraFields adminExtraFields) {
		return adminExtraFieldsService.update(adminExtraFields);
	}

	@RequestMapping( value="/adminExtraFields/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		adminExtraFieldsService.delete(id);
	}
	
}
