/*
 * Created on 24 Þub 2016 ( Time 15:56:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.ChqbllDetailPartial;
import org.demo.business.service.ChqbllDetailPartialService;
import org.demo.web.listitem.ChqbllDetailPartialListItem;

/**
 * Spring MVC controller for 'ChqbllDetailPartial' management.
 */
@Controller
public class ChqbllDetailPartialRestController {

	@Resource
	private ChqbllDetailPartialService chqbllDetailPartialService;
	
	@RequestMapping( value="/items/chqbllDetailPartial",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ChqbllDetailPartialListItem> findAllAsListItems() {
		List<ChqbllDetailPartial> list = chqbllDetailPartialService.findAll();
		List<ChqbllDetailPartialListItem> items = new LinkedList<ChqbllDetailPartialListItem>();
		for ( ChqbllDetailPartial chqbllDetailPartial : list ) {
			items.add(new ChqbllDetailPartialListItem( chqbllDetailPartial ) );
		}
		return items;
	}
	
	@RequestMapping( value="/chqbllDetailPartial",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ChqbllDetailPartial> findAll() {
		return chqbllDetailPartialService.findAll();
	}

	@RequestMapping( value="/chqbllDetailPartial/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ChqbllDetailPartial findOne(@PathVariable("id") Integer id) {
		return chqbllDetailPartialService.findById(id);
	}
	
	@RequestMapping( value="/chqbllDetailPartial",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ChqbllDetailPartial create(@RequestBody ChqbllDetailPartial chqbllDetailPartial) {
		return chqbllDetailPartialService.create(chqbllDetailPartial);
	}

	@RequestMapping( value="/chqbllDetailPartial/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ChqbllDetailPartial update(@PathVariable("id") Integer id, @RequestBody ChqbllDetailPartial chqbllDetailPartial) {
		return chqbllDetailPartialService.update(chqbllDetailPartial);
	}

	@RequestMapping( value="/chqbllDetailPartial/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		chqbllDetailPartialService.delete(id);
	}
	
}
