/*
 * Created on 24 Þub 2016 ( Time 15:56:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.ContactTrans;
import org.demo.business.service.ContactTransService;
import org.demo.web.listitem.ContactTransListItem;

/**
 * Spring MVC controller for 'ContactTrans' management.
 */
@Controller
public class ContactTransRestController {

	@Resource
	private ContactTransService contactTransService;
	
	@RequestMapping( value="/items/contactTrans",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContactTransListItem> findAllAsListItems() {
		List<ContactTrans> list = contactTransService.findAll();
		List<ContactTransListItem> items = new LinkedList<ContactTransListItem>();
		for ( ContactTrans contactTrans : list ) {
			items.add(new ContactTransListItem( contactTrans ) );
		}
		return items;
	}
	
	@RequestMapping( value="/contactTrans",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContactTrans> findAll() {
		return contactTransService.findAll();
	}

	@RequestMapping( value="/contactTrans/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContactTrans findOne(@PathVariable("id") Integer id) {
		return contactTransService.findById(id);
	}
	
	@RequestMapping( value="/contactTrans",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContactTrans create(@RequestBody ContactTrans contactTrans) {
		return contactTransService.create(contactTrans);
	}

	@RequestMapping( value="/contactTrans/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContactTrans update(@PathVariable("id") Integer id, @RequestBody ContactTrans contactTrans) {
		return contactTransService.update(contactTrans);
	}

	@RequestMapping( value="/contactTrans/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		contactTransService.delete(id);
	}
	
}
