/*
 * Created on 24 Þub 2016 ( Time 15:56:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.StockBarcode;
import org.demo.business.service.StockBarcodeService;
import org.demo.web.listitem.StockBarcodeListItem;

/**
 * Spring MVC controller for 'StockBarcode' management.
 */
@Controller
public class StockBarcodeRestController {

	@Resource
	private StockBarcodeService stockBarcodeService;
	
	@RequestMapping( value="/items/stockBarcode",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<StockBarcodeListItem> findAllAsListItems() {
		List<StockBarcode> list = stockBarcodeService.findAll();
		List<StockBarcodeListItem> items = new LinkedList<StockBarcodeListItem>();
		for ( StockBarcode stockBarcode : list ) {
			items.add(new StockBarcodeListItem( stockBarcode ) );
		}
		return items;
	}
	
	@RequestMapping( value="/stockBarcode",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<StockBarcode> findAll() {
		return stockBarcodeService.findAll();
	}

	@RequestMapping( value="/stockBarcode/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public StockBarcode findOne(@PathVariable("id") Integer id) {
		return stockBarcodeService.findById(id);
	}
	
	@RequestMapping( value="/stockBarcode",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public StockBarcode create(@RequestBody StockBarcode stockBarcode) {
		return stockBarcodeService.create(stockBarcode);
	}

	@RequestMapping( value="/stockBarcode/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public StockBarcode update(@PathVariable("id") Integer id, @RequestBody StockBarcode stockBarcode) {
		return stockBarcodeService.update(stockBarcode);
	}

	@RequestMapping( value="/stockBarcode/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		stockBarcodeService.delete(id);
	}
	
}
