/*
 * Created on 24 Þub 2016 ( Time 15:56:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.Stock;
import org.demo.business.service.StockService;
import org.demo.web.listitem.StockListItem;

/**
 * Spring MVC controller for 'Stock' management.
 */
@Controller
public class StockRestController {

	@Resource
	private StockService stockService;
	
	@RequestMapping( value="/items/stock",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<StockListItem> findAllAsListItems() {
		List<Stock> list = stockService.findAll();
		List<StockListItem> items = new LinkedList<StockListItem>();
		for ( Stock stock : list ) {
			items.add(new StockListItem( stock ) );
		}
		return items;
	}
	
	@RequestMapping( value="/stock",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Stock> findAll() {
		return stockService.findAll();
	}

	@RequestMapping( value="/stock/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Stock findOne(@PathVariable("id") Integer id) {
		return stockService.findById(id);
	}
	
	@RequestMapping( value="/stock",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Stock create(@RequestBody Stock stock) {
		return stockService.create(stock);
	}

	@RequestMapping( value="/stock/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Stock update(@PathVariable("id") Integer id, @RequestBody Stock stock) {
		return stockService.update(stock);
	}

	@RequestMapping( value="/stock/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		stockService.delete(id);
	}
	
}
