/*
 * Created on 24 Þub 2016 ( Time 15:56:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.TempContactAging;
import org.demo.business.service.TempContactAgingService;
import org.demo.web.listitem.TempContactAgingListItem;

/**
 * Spring MVC controller for 'TempContactAging' management.
 */
@Controller
public class TempContactAgingRestController {

	@Resource
	private TempContactAgingService tempContactAgingService;
	
	@RequestMapping( value="/items/tempContactAging",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TempContactAgingListItem> findAllAsListItems() {
		List<TempContactAging> list = tempContactAgingService.findAll();
		List<TempContactAgingListItem> items = new LinkedList<TempContactAgingListItem>();
		for ( TempContactAging tempContactAging : list ) {
			items.add(new TempContactAgingListItem( tempContactAging ) );
		}
		return items;
	}
	
	@RequestMapping( value="/tempContactAging",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TempContactAging> findAll() {
		return tempContactAgingService.findAll();
	}

	@RequestMapping( value="/tempContactAging/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TempContactAging findOne(@PathVariable("id") Integer id) {
		return tempContactAgingService.findById(id);
	}
	
	@RequestMapping( value="/tempContactAging",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TempContactAging create(@RequestBody TempContactAging tempContactAging) {
		return tempContactAgingService.create(tempContactAging);
	}

	@RequestMapping( value="/tempContactAging/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TempContactAging update(@PathVariable("id") Integer id, @RequestBody TempContactAging tempContactAging) {
		return tempContactAgingService.update(tempContactAging);
	}

	@RequestMapping( value="/tempContactAging/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		tempContactAgingService.delete(id);
	}
	
}
