/*
 * JUnit test case for GlobalProfile caching service
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.cache;


import org.demo.bean.GlobalProfile ;
import org.demo.cache.GlobalProfileCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for GlobalProfile caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class GlobalProfileCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(GlobalProfile globalProfile) {
		globalProfile.setId( 1 ) ;
		globalProfile.setName( "A" ) ;
		globalProfile.setDescription( "A" ) ;
		globalProfile.setIsActive( false ) ;
		globalProfile.setJsonData( "A" ) ;
		globalProfile.setVersion( 1 ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class GlobalProfileCache ..." );
		
		GlobalProfile globalProfile = new GlobalProfile();
		populate(globalProfile);
		System.out.println("Entity populated : " + globalProfile );
		
		GlobalProfileCache.putGlobalProfile(globalProfile) ;	// Store in cache	
		
		GlobalProfile globalProfile2 = GlobalProfileCache.getGlobalProfile( globalProfile.getId() );
		Assert.assertTrue( globalProfile == globalProfile2 ) ; // Same instance
		
		GlobalProfileCache.removeGlobalProfile(  globalProfile.getId() ) ; // Remove from cache	
		
		GlobalProfile globalProfile3 = GlobalProfileCache.getGlobalProfile( globalProfile.getId() );
		Assert.assertTrue( null == globalProfile3 ) ; // Not in cache
		
	}
}
