/*
 * JUnit test case for OrderTransStatus caching service
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.cache;


import org.demo.bean.OrderTransStatus ;
import org.demo.cache.OrderTransStatusCache ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for OrderTransStatus caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrderTransStatusCacheTest 
{
	protected static final java.util.Date now = new java.util.Date();

	private final static void populate(OrderTransStatus orderTransStatus) {
		orderTransStatus.setId( 1 ) ;
		orderTransStatus.setParentId( 1 ) ;
		orderTransStatus.setName( "A" ) ;
		orderTransStatus.setOrdering( 1 ) ;
		orderTransStatus.setInsertBy( "A" ) ;
		orderTransStatus.setInsertAt( now ) ;
		orderTransStatus.setUpdateBy( "A" ) ;
		orderTransStatus.setUpdateAt( now ) ;
		orderTransStatus.setIsActive( false ) ;
		orderTransStatus.setWorkspace( 1 ) ;
		orderTransStatus.setVersion( 1 ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class OrderTransStatusCache ..." );
		
		OrderTransStatus orderTransStatus = new OrderTransStatus();
		populate(orderTransStatus);
		System.out.println("Entity populated : " + orderTransStatus );
		
		OrderTransStatusCache.putOrderTransStatus(orderTransStatus) ;	// Store in cache	
		
		OrderTransStatus orderTransStatus2 = OrderTransStatusCache.getOrderTransStatus( orderTransStatus.getId() );
		Assert.assertTrue( orderTransStatus == orderTransStatus2 ) ; // Same instance
		
		OrderTransStatusCache.removeOrderTransStatus(  orderTransStatus.getId() ) ; // Remove from cache	
		
		OrderTransStatus orderTransStatus3 = OrderTransStatusCache.getOrderTransStatus( orderTransStatus.getId() );
		Assert.assertTrue( null == orderTransStatus3 ) ; // Not in cache
		
	}
}
