/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.ChqbllType ;

/**
 * Very basic cache for ChqbllType instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class ChqbllTypeCache
{
	private final static Map<String,ChqbllType> cache = new Hashtable<String,ChqbllType>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given ChqbllType instance in the cache
	 * @param ChqbllType instance to be stored
	 */
	public final static void putChqbllType(ChqbllType chqbllType ) {
		String key = getKey( chqbllType.getId() ) ;
		cache.put(key, chqbllType );
	}
	
	/**
	 * Get the ChqbllType instance for the given primary key
     * @param id 
	 * @return the ChqbllType instance (or null if none)
	 */
	public final static ChqbllType getChqbllType( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the ChqbllType associated with the given primary key
     * @param id 
	 */
	public final static void removeChqbllType ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given ChqbllType from the cache using its primary key
	 * @param ChqbllType instance to be removed
	 */
	public final static void removeChqbllType (ChqbllType chqbllType ) { 
		String key = getKey( chqbllType.getId() ) ;
		cache.remove(key);
	}

}
