/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.InvoiceTransRelation ;

/**
 * Very basic cache for InvoiceTransRelation instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class InvoiceTransRelationCache
{
	private final static Map<String,InvoiceTransRelation> cache = new Hashtable<String,InvoiceTransRelation>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given InvoiceTransRelation instance in the cache
	 * @param InvoiceTransRelation instance to be stored
	 */
	public final static void putInvoiceTransRelation(InvoiceTransRelation invoiceTransRelation ) {
		String key = getKey( invoiceTransRelation.getId() ) ;
		cache.put(key, invoiceTransRelation );
	}
	
	/**
	 * Get the InvoiceTransRelation instance for the given primary key
     * @param id 
	 * @return the InvoiceTransRelation instance (or null if none)
	 */
	public final static InvoiceTransRelation getInvoiceTransRelation( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the InvoiceTransRelation associated with the given primary key
     * @param id 
	 */
	public final static void removeInvoiceTransRelation ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given InvoiceTransRelation from the cache using its primary key
	 * @param InvoiceTransRelation instance to be removed
	 */
	public final static void removeInvoiceTransRelation (InvoiceTransRelation invoiceTransRelation ) { 
		String key = getKey( invoiceTransRelation.getId() ) ;
		cache.remove(key);
	}

}
