/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.InvoiceTransStatusHistory ;

/**
 * Very basic cache for InvoiceTransStatusHistory instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class InvoiceTransStatusHistoryCache
{
	private final static Map<String,InvoiceTransStatusHistory> cache = new Hashtable<String,InvoiceTransStatusHistory>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given InvoiceTransStatusHistory instance in the cache
	 * @param InvoiceTransStatusHistory instance to be stored
	 */
	public final static void putInvoiceTransStatusHistory(InvoiceTransStatusHistory invoiceTransStatusHistory ) {
		String key = getKey( invoiceTransStatusHistory.getId() ) ;
		cache.put(key, invoiceTransStatusHistory );
	}
	
	/**
	 * Get the InvoiceTransStatusHistory instance for the given primary key
     * @param id 
	 * @return the InvoiceTransStatusHistory instance (or null if none)
	 */
	public final static InvoiceTransStatusHistory getInvoiceTransStatusHistory( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the InvoiceTransStatusHistory associated with the given primary key
     * @param id 
	 */
	public final static void removeInvoiceTransStatusHistory ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given InvoiceTransStatusHistory from the cache using its primary key
	 * @param InvoiceTransStatusHistory instance to be removed
	 */
	public final static void removeInvoiceTransStatusHistory (InvoiceTransStatusHistory invoiceTransStatusHistory ) { 
		String key = getKey( invoiceTransStatusHistory.getId() ) ;
		cache.remove(key);
	}

}
