/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.OrderTransSource ;

/**
 * Very basic cache for OrderTransSource instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrderTransSourceCache
{
	private final static Map<String,OrderTransSource> cache = new Hashtable<String,OrderTransSource>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given OrderTransSource instance in the cache
	 * @param OrderTransSource instance to be stored
	 */
	public final static void putOrderTransSource(OrderTransSource orderTransSource ) {
		String key = getKey( orderTransSource.getId() ) ;
		cache.put(key, orderTransSource );
	}
	
	/**
	 * Get the OrderTransSource instance for the given primary key
     * @param id 
	 * @return the OrderTransSource instance (or null if none)
	 */
	public final static OrderTransSource getOrderTransSource( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the OrderTransSource associated with the given primary key
     * @param id 
	 */
	public final static void removeOrderTransSource ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given OrderTransSource from the cache using its primary key
	 * @param OrderTransSource instance to be removed
	 */
	public final static void removeOrderTransSource (OrderTransSource orderTransSource ) { 
		String key = getKey( orderTransSource.getId() ) ;
		cache.remove(key);
	}

}
