/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.StockExtraFields ;

/**
 * Very basic cache for StockExtraFields instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class StockExtraFieldsCache
{
	private final static Map<String,StockExtraFields> cache = new Hashtable<String,StockExtraFields>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given StockExtraFields instance in the cache
	 * @param StockExtraFields instance to be stored
	 */
	public final static void putStockExtraFields(StockExtraFields stockExtraFields ) {
		String key = getKey( stockExtraFields.getId() ) ;
		cache.put(key, stockExtraFields );
	}
	
	/**
	 * Get the StockExtraFields instance for the given primary key
     * @param id 
	 * @return the StockExtraFields instance (or null if none)
	 */
	public final static StockExtraFields getStockExtraFields( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the StockExtraFields associated with the given primary key
     * @param id 
	 */
	public final static void removeStockExtraFields ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given StockExtraFields from the cache using its primary key
	 * @param StockExtraFields instance to be removed
	 */
	public final static void removeStockExtraFields (StockExtraFields stockExtraFields ) { 
		String key = getKey( stockExtraFields.getId() ) ;
		cache.remove(key);
	}

}
