/*
 * Very basic JavaBean cache
 * Created on 24 Þub 2016 ( Date ISO 2016-02-24 - Time 15:13:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.bean.StockBarcode ;

/**
 * Very basic cache for StockBarcode instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class StockBarcodeCache
{
	private final static Map<String,StockBarcode> cache = new Hashtable<String,StockBarcode>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( Integer id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given StockBarcode instance in the cache
	 * @param StockBarcode instance to be stored
	 */
	public final static void putStockBarcode(StockBarcode stockBarcode ) {
		String key = getKey( stockBarcode.getId() ) ;
		cache.put(key, stockBarcode );
	}
	
	/**
	 * Get the StockBarcode instance for the given primary key
     * @param id 
	 * @return the StockBarcode instance (or null if none)
	 */
	public final static StockBarcode getStockBarcode( Integer id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the StockBarcode associated with the given primary key
     * @param id 
	 */
	public final static void removeStockBarcode ( Integer id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given StockBarcode from the cache using its primary key
	 * @param StockBarcode instance to be removed
	 */
	public final static void removeStockBarcode (StockBarcode stockBarcode ) { 
		String key = getKey( stockBarcode.getId() ) ;
		cache.remove(key);
	}

}
